import { useEffect, useState, useRef, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { io, Socket } from 'socket.io-client';
import { motion, AnimatePresence } from 'framer-motion';
import { generateKeyPair, exportPublicKey, importPublicKey, deriveSharedKey } from '../lib/crypto';
import { sendFilePipeline, ReceiverPipeline } from '../lib/pipeline';
import { WebRTCManager } from '../lib/webrtc';
import { processFile } from '../lib/compression';
import { getCompressionStats } from '../lib/stats';
import { FilePicker } from './FilePicker';
import { TransferProgressStages, type TransferStage } from './TransferProgressStages';
import {
  Cpu,
  Wifi,
  Download,
  Bell,
  Lock,
  Activity,
  Layers,
  Zap,
  Terminal,
  Loader2,
  Users,
  Play,
  LogOut,
  ShieldAlert,
  Search,
  UserX,
  ChevronDown,
  ShieldCheck,
  Globe,
  Info,
  UserPlus,
  ArrowLeft,
} from 'lucide-react';
import clsx from 'clsx';

// Type for compression formats supported by DecompressionStream
type CompressionFormat = 'deflate' | 'gzip';

// --- THEME CONFIGURATION ---
const COLORS = {
  bg: '#0B0F14',
  surface: '#121826',
  text: '#E5E7EB',
  accent: '#3B82F6'
};

/**
 * 🛠 HELPER: ROBUST DECOMPRESSION
 * Handles the specific names generated by our heuristic logic.
 */
const decompressBlob = async (blob: Blob, algo: string, fileName: string): Promise<Blob> => {
  try {
    console.log(`[Decompress] STARTING - algo: "${algo}", fileName: "${fileName}", blob size: ${blob.size}`);
    
    // 1. If logic said "Store", we do NOT decompress
    if (algo.startsWith('Store')) {
      console.log(`[Decompress] Detected Store algo - returning blob as-is`);
      return blob;
    }

    let format: CompressionFormat | null = null;

    // 2. Check Explicit Algorithm Label
    if (algo.includes('Deflate')) {
        format = 'deflate';
        console.log(`[Decompress] Matched "Deflate" - using deflate`);
    }
    else if (algo.includes('Gzip')) {
        format = 'gzip';
        console.log(`[Decompress] Matched "Gzip" - using gzip`);
    }
    // 3. Fallback: Extension
    else if (fileName.endsWith('.gz')) {
        format = 'gzip';
        console.log(`[Decompress] Matched .gz extension - using gzip`);
    }

    if (!format) {
      console.log(`[Decompress] NO FORMAT MATCHED for algo: "${algo}"`);
      return blob;
    }

    console.log(`[Decompress] Using format: ${format}, input size: ${blob.size} bytes`);
    
    // Get the raw blob data first to verify it's not empty
    const blobBuffer = await blob.arrayBuffer();
    console.log(`[Decompress] Blob buffer size: ${blobBuffer.byteLength} bytes`);
    
    if (blobBuffer.byteLength === 0) {
      console.error(`[Decompress] ERROR: Received empty blob! Cannot decompress.`);
      return blob;
    }
    
    try {
      console.log(`[Decompress] Creating DecompressionStream with format: ${format}`);
      const ds = new DecompressionStream(format);
      const decompressedStream = blob.stream().pipeThrough(ds);
      const decompressedBlob = await new Response(decompressedStream).blob();
      
      console.log(`[Decompress] SUCCESS! Decompressed size: ${decompressedBlob.size} bytes`);
      
      if (decompressedBlob.size === 0) {
        console.error(`[Decompress] ERROR: Decompression produced empty blob!`);
        return blob;
      }
      
      return decompressedBlob;
    } catch (decompressError) {
      console.error(`[Decompress] DecompressionStream FAILED:`, decompressError);
      console.log(`[Decompress] Returning original blob as fallback`);
      return blob;
    }
  } catch (error) {
    console.error("[Decompress] CRITICAL ERROR:", error);
    console.error("[Decompress] Algo:", algo, "File:", fileName, "Blob size:", blob.size);
    return blob;
  }
};

const SERVER_URL = import.meta.env.VITE_SERVER_URL || 'https://smartstream-algoquest.onrender.com';
const socket: Socket = io(SERVER_URL, {
  transports: ['websocket', 'polling'],
  reconnectionAttempts: 10,
  reconnectionDelay: 1000
});

export const TransferRoom = () => {
  const navigate = useNavigate();

  // Helper function to generate unique 6-character room ID (lowercase letters + numbers)
  const generateRoomId = (): string => {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    let roomId = '';
    for (let i = 0; i < 6; i++) {
      roomId += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return roomId;
  };

  // --- CORE IDENTITY STATE ---
  const [username] = useState(localStorage.getItem('username') || '');
  const [status, setStatus] = useState('Initializing Systems...');
  const [, setP2pState] = useState<string>('disconnected');

  // --- NETWORKING: ROOMS & DISCOVERY ---
  const [roomId, setRoomId] = useState('');
  const [isJoined, setIsJoined] = useState(false);
  const [roomMode, setRoomMode] = useState<'select' | 'create' | 'join' | 'addUser'>('select'); // 'select' = show Create/Join buttons, 'create' = room created, 'join' = joining, 'addUser' = search user by ID
  const [joinRoomInput, setJoinRoomInput] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResult, setSearchResult] = useState<string | null>(null);
  const [isSearching, setIsSearching] = useState(false);
  const [verifiedUser, setVerifiedUser] = useState<{ name: string, status: string } | null>(null);
  
  // Stores request info: { from: 'Alice', key: JsonWebKey, id: 'socket_id_123' }
  const [incomingRequest, setIncomingRequest] = useState<{ from: string, key: JsonWebKey, id: string } | null>(null);

  // --- MESH TOPOLOGY STATE ---
  const [peers, setPeers] = useState<{ id: string, username: string, status: string }[]>([]);
  const peersRef = useRef<Map<string, WebRTCManager>>(new Map());
  const keysRef = useRef<Map<string, CryptoKey>>(new Map());
  const keyPairRef = useRef<CryptoKeyPair | null>(null);
  const receiverPipelineRef = useRef<ReceiverPipeline | null>(null);
  const lastAckRef = useRef<string>('');

  // --- UI & PIPELINE MONITORING ---
  const [isTransferring, setIsTransferring] = useState(false);
  const [encryptionReady, setEncryptionReady] = useState(false);
  const [progress, setProgress] = useState(0);
  const [logs, setLogs] = useState<string[]>([]);
  const [receivedFiles, setReceivedFiles] = useState<{ name: string, url: string }[]>([]);
  const [transferStats, setTransferStats] = useState<any>(null);
  const [queueStatus, setQueueStatus] = useState('');
  const [advancedStats, setAdvancedStats] = useState<any>(null);
  const [transferStage, setTransferStage] = useState<TransferStage>('idle');
  const [currentFileName, setCurrentFileName] = useState('');
  const [showAddUserPanel, setShowAddUserPanel] = useState(false);

  // Terminal Logger
  const addLog = (msg: string) => setLogs(prev => [...prev.slice(-19), `${new Date().toLocaleTimeString()} - ${msg}`]);

  // =========================================
  // 1. CONNECTION FACTORY (WebRTC HANDSHAKE)
  // =========================================
  const createPeerConnection = useCallback((targetId: string, isInitiator: boolean) => {
    console.log(`[createPeerConnection] Creating ${isInitiator ? 'INITIATOR' : 'NON-INITIATOR'} connection to ${targetId}`);
    
    if (peersRef.current.has(targetId)) {
      console.log(`[createPeerConnection] Connection already exists for ${targetId}`);
      return peersRef.current.get(targetId)!;
    }

    const manager = new WebRTCManager(socket, targetId,
      (data) => handleIncomingData(data, targetId),
      (state) => {
        console.log(`[WebRTC] State change for ${targetId}: ${state}`);
        setPeers(prev => prev.map(p => p.id === targetId ? { ...p, status: state } : p));
        if (state === 'connected') {
          setP2pState('connected');
          if (keyPairRef.current) {
            exportPublicKey(keyPairRef.current.publicKey).then(k => {
              console.log(`[WebRTC] Sending pub-key to ${targetId}`);
              socket.emit('signal', { target: targetId, payload: { type: 'pub-key', key: k } });
            });
          }
        } else if (state === 'failed' || state === 'closed') {
          console.log(`[WebRTC] Closing connection to ${targetId}`);
          peersRef.current.delete(targetId);
          keysRef.current.delete(targetId);
        }
      }
    );

    console.log(`[createPeerConnection] Initializing connection, isInitiator=${isInitiator}`);
    manager.initConnection(isInitiator);
    peersRef.current.set(targetId, manager);
    console.log(`[createPeerConnection] Connection created and stored, total managers: ${peersRef.current.size}`);
    return manager;
  }, [socket, username]);

  // =========================================
  // 2. INITIALIZATION & SOCKET BUS
  // =========================================
  useEffect(() => {
    if (!username) { navigate('/auth'); return; }

    generateKeyPair().then(keys => {
      keyPairRef.current = keys;
      addLog("Local Identity ECDH Keys Generated");
    });

    socket.emit('register-user', username);
    setStatus('Online');

    socket.on('connect', () => { setStatus('Online'); socket.emit('register-user', username); });
    socket.on('disconnect', () => { setStatus('Offline'); setEncryptionReady(false); });

    socket.on('user-status', (data: any) => {
      setIsSearching(false);
      if (data.status === 'online') {
        setSearchResult(data.username);
        setVerifiedUser({ name: data.username, status: 'Online' });
      } else {
        setSearchResult(null);
        setVerifiedUser(null);
      }
    });

    socket.on('signal', async ({ sender, payload }) => {
      let manager = peersRef.current.get(sender);

      if (!manager) {
        setPeers(prev => prev.find(p => p.id === sender) ? prev : [...prev, { id: sender, username: `Guest_${sender.slice(0, 4)}`, status: 'Connecting...' }]);
        manager = createPeerConnection(sender, false);
        // Ensure manager is properly initialized before handling signal
        if (!manager) {
          console.error(`Failed to create peer connection for ${sender}`);
          return;
        }
      }

      if (manager) {
        await manager.handleSignal(payload);
      }

      // ✅ CAPTURE SENDER ID HERE
      if (payload.type === 'conn-request') {
        setIncomingRequest({ 
            from: payload.username || sender, 
            key: payload.key,
            id: sender // Store the Socket ID to reply later
        });
      }

      if (payload.type === 'pub-key') {
        try {
          const foreignKey = await importPublicKey(payload.key);
          if (keyPairRef.current) {
            const shared = await deriveSharedKey(keyPairRef.current.privateKey, foreignKey);
            keysRef.current.set(sender, shared);
            addLog(`🔐 AES-256 secure tunnel synced with ${sender.slice(0, 4)}`);
            setEncryptionReady(true);
            setPeers(prev => prev.map(p => p.id === sender ? { ...p, status: 'connected' } : p));
          }
        } catch (e) { console.error("Identity Handshake Failed:", e); }
      }
    });

    socket.on('user-joined', ({ id, username }) => {
      console.log(`[Socket] User joined: ${username} (${id})`);
      addLog(`${username} entered the mesh.`);
      setPeers(prev => prev.find(p => p.id === id) ? prev : [...prev, { id, username, status: 'Connecting...' }]);
      const manager = createPeerConnection(id, false);
      if (!manager) {
        console.error(`Failed to create peer connection for new user ${id}`);
      }
    });

    socket.on('existing-users', (users) => {
      console.log(`[Socket] Existing users received: ${users.length} users`);
      users.forEach((u: any) => {
        console.log(`[Socket] Creating initiator connection to ${u.username} (${u.id})`);
        setPeers(prev => prev.find(p => p.id === u.id) ? prev : [...prev, { id: u.id, username: u.username, status: 'Connecting...' }]);
        const manager = createPeerConnection(u.id, true);
        if (!manager) {
          console.error(`Failed to create peer connection for existing user ${u.id}`);
        }
      });
    });

    socket.on('user-left', (id) => {
      addLog(`User disconnected.`);
      peersRef.current.get(id)?.close();
      peersRef.current.delete(id);
      keysRef.current.delete(id);
      setPeers(prev => prev.filter(p => p.id !== id));
      if (peersRef.current.size === 0) setEncryptionReady(false);
    });

    return () => {
      socket.off('signal');
      socket.off('user-joined');
      socket.off('existing-users');
      socket.off('user-left');
      socket.off('user-status');
      socket.off('connect');
      socket.off('disconnect');
    };
  }, [username, navigate, createPeerConnection]);

  // =========================================
  // 3. SEARCH & USER DISCOVERY
  // =========================================
  useEffect(() => {
    const delayDebounceFn = setTimeout(() => {
      if (searchQuery.length > 2 && searchQuery !== username) {
        setIsSearching(true);
        socket.emit('check-user', searchQuery);
      } else {
        setSearchResult(null); setVerifiedUser(null); setIsSearching(false);
      }
    }, 500);
    return () => clearTimeout(delayDebounceFn);
  }, [searchQuery, username]);

  // =========================================
  // 4. USER INTERACTION HANDLERS
  // =========================================
  const handleCreateRoom = () => {
    const newRoomId = generateRoomId();
    setRoomId(newRoomId);
    setRoomMode('create');
    console.log(`[Room] Created new room with ID: ${newRoomId}`);
    socket.emit('join-room', newRoomId, username);
    setIsJoined(true);
    addLog(`Created Private Mesh Room: ${newRoomId}`);
  };

  const handleJoinRoom = () => {
    const idToJoin = joinRoomInput.trim().toLowerCase();
    if (!idToJoin) return alert("Please enter a Room ID");
    if (idToJoin.length !== 6) return alert("Room ID must be exactly 6 characters");
    console.log(`[Room] Attempting to join room: ${idToJoin} as user: ${username}`);
    socket.emit('join-room', idToJoin, username);
    setRoomId(idToJoin);
    setRoomMode('join');
    setIsJoined(true);
    addLog(`Joined Private Mesh Room: ${idToJoin}`);
  };

  const handleDirectConnect = async (targetUsername: string) => {
    try {
      // Ensure we have a local keypair ready
      if (!keyPairRef.current) {
        const keys = await generateKeyPair();
        keyPairRef.current = keys;
        addLog("Local Identity ECDH Keys Generated (on-demand)");
      }

      const cleanTarget = targetUsername.trim().toLowerCase();
      const pubKey = await exportPublicKey(keyPairRef.current!.publicKey);

      socket.emit('signal', {
        target: cleanTarget,
        payload: { type: 'conn-request', key: pubKey, username }
      });

      addLog(`Broadcasting Direct Connection Request to @${cleanTarget}...`);
    } catch (e) {
      console.error("Direct connect failed:", e);
      addLog("❌ Direct connect failed");
    }
  };

  // ✅ COMPLETE HANDSHAKE LOGIC
  const acceptRequest = async () => {
    if (!incomingRequest || !keyPairRef.current) return;

    try {
        const { id: senderId, key: foreignKeyJson, from } = incomingRequest;
        addLog(`🔐 Establishing secure tunnel with ${from}...`);

        // 1. Import their key
        const foreignKey = await importPublicKey(foreignKeyJson);
        
        // 2. Derive shared secret
        const sharedKey = await deriveSharedKey(keyPairRef.current.privateKey, foreignKey);
        
        // 3. Save key mapped to their Socket ID
        keysRef.current.set(senderId, sharedKey);
        
        // 4. Send OUR public key back
        const myPublicKey = await exportPublicKey(keyPairRef.current.publicKey);
        socket.emit('signal', { 
            target: senderId, 
            payload: { type: 'pub-key', key: myPublicKey, username } 
        });

        // 5. Update UI
        setEncryptionReady(true);
        setPeers(prev => {
            if (prev.find(p => p.id === senderId)) return prev.map(p => p.id === senderId ? {...p, status: 'connected'} : p);
            return [...prev, { id: senderId, username: from, status: 'connected' }];
        });

        addLog(`✅ Secure Connection Established`);
    } catch (e) {
        console.error("Handshake failed", e);
        addLog("❌ Handshake Failed");
    }

    setIncomingRequest(null);
  };

  const handleLogout = () => {
    localStorage.clear();
    socket.disconnect();
    peersRef.current.forEach(p => p.close());
    navigate('/auth');
  };

  // =========================================
  // 5. RECEIVER ENGINE (INBOUND DATA PROCESSING)
  // =========================================
  const handleIncomingData = async (data: ArrayBuffer, senderId: string) => {
    try {
      const text = new TextDecoder().decode(data);
      if (text.trim().startsWith('{')) {
        const msg = JSON.parse(text);

        if (msg.type === 'file-start') {          console.log(`[Receiver] Received file-start metadata:`, msg);          
        setIsTransferring(true);
          setCurrentFileName(msg.name);
          setTransferStage('transferred');
          addLog(`⬇️ Receiving: ${msg.name}`);
          setProgress(0);
          const sharedKey = keysRef.current.get(senderId);
          if (sharedKey) {
            receiverPipelineRef.current = new ReceiverPipeline(sharedKey, msg.algo, async (blob, stats) => {
              setTransferStage('decrypting');
              setQueueStatus("Decrypting & Reassembling...");

              try {
                console.log(`[Receiver] Received blob - size: ${blob.size}, algo: ${msg.algo}, name: ${msg.name}`);

                // 1. Verify received blob is not empty
                if (blob.size === 0) {
                  console.error(`[Receiver] ERROR: Received empty blob! Cannot process file.`);
                  addLog(`❌ Received corrupted file (empty blob)`);
                  setIsTransferring(false);
                  setQueueStatus('');
                  return;
                }

                setTransferStage('decrypted');

                // 2. Decompress the received (decrypted) blob
                setTransferStage('decompressing');
                const decompressedBlob = await decompressBlob(blob, msg.algo, msg.name);
                setTransferStage('decompressed');
                console.log(`[Receiver] After decompression - size: ${decompressedBlob.size}`);

                // 3. Verify decompression didn't return empty blob
                if (decompressedBlob.size === 0) {
                  console.error(`[Receiver] ERROR: Decompression resulted in empty blob!`);
                  addLog(`❌ File decompression failed - corrupted data`);
                  setIsTransferring(false);
                  setQueueStatus('');
                  return;
                }

                // 4. Get original file data as bytes to verify integrity
                const arrayBuffer = await decompressedBlob.arrayBuffer();
                const uint8array = new Uint8Array(arrayBuffer);
                console.log(`[Receiver] Decompressed data verified - ${uint8array.length} bytes`);

                // 5. MIME-TYPE ENFORCEMENT - Set correct MIME type based on file extension
                const lowerName = msg.name.toLowerCase();
                let finalMime = 'application/octet-stream';
                
                if (lowerName.endsWith('.pdf')) {
                  finalMime = 'application/pdf';
                  console.log(`[Receiver] Detected PDF file - MIME type: ${finalMime}`);
                } else if (lowerName.endsWith('.ipynb')) {
                  finalMime = 'application/x-ipynb+json';
                } else if (lowerName.endsWith('.json')) {
                  finalMime = 'application/json';
                } else if (lowerName.endsWith('.txt')) {
                  finalMime = 'text/plain';
                } else if (lowerName.endsWith('.png')) {
                  finalMime = 'image/png';
                } else if (lowerName.endsWith('.jpg') || lowerName.endsWith('.jpeg')) {
                  finalMime = 'image/jpeg';
                } else if (lowerName.endsWith('.zip')) {
                  finalMime = 'application/zip';
                }

                const correctedBlob = new Blob([uint8array], { type: finalMime });
                console.log(`[Receiver] Final blob created - size: ${correctedBlob.size}, mime: ${finalMime}`);

                // 6. Extension Cleanup - Remove compression extensions
                const finalName = msg.name.replace(/\.gz$/, "").replace(/\.br$/, "").replace(/\.deflate$/, "");
                const url = URL.createObjectURL(correctedBlob);
                
                setReceivedFiles(prev => [...prev, { name: finalName, url }]);
                setTransferStage('complete');
                console.log(`[Receiver] File ready for download: ${finalName}`);

                // 7. Update Stats with compression percentage
                // Use msg.originalSize (sent by sender) as the original file size
                // blob.size is the compressed (but decrypted) file size
                const senderOriginalSize = msg.originalSize || correctedBlob.size;
                const receiverStats = getCompressionStats(senderOriginalSize, blob.size);
                setTransferStats({
                  ...stats,
                  originalSize: senderOriginalSize, // Original file size from sender
                  finalSize: blob.size,              // Size after decryption (compressed)
                  compressionPercent: receiverStats.compressionPercent,
                  compressionRatio: receiverStats.compressionRatio
                });

                addLog(`✅ File Integrated: ${finalName}`);
                setProgress(100);
                setIsTransferring(false);
                setQueueStatus('');
                
                // 8. Send acknowledgment
                const ackMsg = JSON.stringify({ type: 'file-ack', name: msg.name });
                const ackBuffer = new TextEncoder().encode(ackMsg);
                peersRef.current.get(senderId)?.sendData(ackBuffer.buffer as ArrayBuffer);
              } catch (error) {
                console.error('[Receiver] Error processing file:', error);
                addLog(`❌ File processing failed: ${error}`);
                setIsTransferring(false);
                setQueueStatus('');
              }
            });
          }
        }
        else if (msg.type === 'file-end') {
          setTimeout(() => receiverPipelineRef.current?.finish(), 250);
        }
        else if (msg.type === 'file-ack') {
          lastAckRef.current = msg.name;
        }
        return;
      }
    } catch (e) {
      console.warn("Pipeline metadata parsing failed, treating as binary chunk.");
    }

    if (receiverPipelineRef.current) {
      receiverPipelineRef.current.processChunk(data);
      setProgress(p => (p >= 98 ? 98 : p + 0.5));
    }
  };

  // =========================================
  // 6. SENDER ENGINE (SEQUENTIAL BROADCAST)
  // =========================================
  const startBatchTransfer = async (files: File[]) => {
    if (peersRef.current.size === 0) return alert("Mesh Network Empty. Join a room first.");

    setIsTransferring(true);
    const encoder = new TextEncoder();

    try {
      for (let i = 0; i < files.length; i++) {
        const originalFile = files[i];
        setCurrentFileName(originalFile.name);
        setTransferStage('algo-selected');
        setQueueStatus(`Pre-Transfer Security Scan...`);

        // 1. Process File (Forced Compression)
        setTransferStage('compressing');
        const { file: processedData, meta } = await processFile(originalFile);
        setTransferStage('compressed');
        // IMPORTANT: Always use the algorithm that was actually used for compression (meta.algorithm)
        // Do NOT override with analyzeFile recommendation, as that could cause mismatch between
        // what was actually compressed vs what we tell the receiver to decompress with
        const algoName = meta.algorithm;
        
        console.log(`[Sender] File: ${originalFile.name}`);
        console.log(`[Sender] Meta algorithm from processFile: ${meta.algorithm}`);
        console.log(`[Sender] Final algorithm to use: ${algoName}`);
        console.log(`[Sender] Original size: ${meta.originalSize}, Compressed size: ${meta.compressedSize}`);

        // 2. Set Stats
        setAdvancedStats(meta);

        // 3. Security Block
        if (meta.securityStatus === 'Suspicious') {
          alert(`🚫 SECURITY BLOCK TRIGGERED\nFile: ${originalFile.name}\nRisk Score: ${meta.riskScore}%\nReason: ${meta.reason}`);
          addLog(`🚫 Blocked potentially harmful file: ${originalFile.name}`);
          continue;
        }

        addLog(`🤖 Intelligence: Applied ${algoName} Strategy`);

        const activePeers = Array.from(peersRef.current.entries());
        let peerCount = 1;

        for (const [peerId, manager] of activePeers) {
          const sharedKey = keysRef.current.get(peerId);
          if (!sharedKey || !manager.dataChannel || manager.dataChannel.readyState !== 'open') continue;

          setQueueStatus(`Mesh Broadcast: Target ${peerCount}/${activePeers.length}...`);
          setProgress(0);

          // 4. Send Metadata (with original file size for compression percentage calculation)
          setTransferStage('encrypting');
          const metaObj = { type: 'file-start', name: originalFile.name, algo: algoName, originalSize: meta.originalSize };
          console.log(`[Sender] Sending file-start metadata:`, metaObj);
          const startMeta = encoder.encode(JSON.stringify(metaObj));
          await manager.sendData(startMeta.buffer as ArrayBuffer);
          setTransferStage('encrypted');

          // 5. Send Binary Pipeline
          setTransferStage('transferring');
          const transferResult = await sendFilePipeline(processedData as any, sharedKey, algoName, async (chunk) => {
            await manager.sendData(chunk);
            setProgress(p => (p >= 98 ? 98 : p + 0.5));
          });
          setTransferStage('transferred');

          // 6. Update Stats for Sender (Using unified compression stats utility)
          const stats = getCompressionStats(meta.originalSize, meta.compressedSize);
          setTransferStats({
            originalSize: stats.originalSize,
            finalSize: stats.compressedSize, 
            speed: transferResult.speed,
            compressionPercent: stats.compressionPercent,
            compressionRatio: stats.compressionRatio
          });

          // Backpressure
          // @ts-ignore
          while (manager.dataChannel?.bufferedAmount > 0) await new Promise(r => setTimeout(r, 100));

          // 7. Send Metadata (End)
          const endMeta = encoder.encode(JSON.stringify({ type: 'file-end', name: originalFile.name }));
          await manager.sendData(endMeta.buffer as ArrayBuffer);

          addLog(`Verifying integrity with Peer ${peerCount}...`);
          await new Promise<void>(resolve => {
            const check = setInterval(() => {
              if (lastAckRef.current === originalFile.name) { clearInterval(check); resolve(); }
            }, 150);
            setTimeout(() => { clearInterval(check); resolve(); }, 10000);
          });

          lastAckRef.current = '';
          peerCount++;
        }

        addLog(`✅ Mesh Broadcast Complete: "${originalFile.name}"`);
        setProgress(100);
      }
      setQueueStatus('');
      addLog("Pipeline Empty - Batch Finished");
    } catch (e) {
      console.error(e);
      addLog("❌ Pipeline Error - Transfer Aborted");
    } finally {
      setIsTransferring(false);
      setProgress(0);
    }
  };

  // =========================================
  // 7. UI RENDER ENGINE
  // =========================================
  return (
    <div className="min-h-screen font-sans selection:bg-blue-500/30" style={{ backgroundColor: COLORS.bg, color: COLORS.text }}>

      {/* GLOBAL NAVBAR */}
      <nav className="sticky top-0 z-50 border-b border-gray-800 bg-[#0B0F14]/80 backdrop-blur-md px-6 h-16 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-blue-600 flex items-center justify-center shadow-lg shadow-blue-900/50">
            <Cpu className="text-white w-5 h-5" />
          </div>
          <div className="flex flex-col">
            <span className="font-bold text-xl tracking-tight text-white leading-tight">SmartStream</span>
            <span className="text-blue-500 text-[10px] font-bold tracking-[0.2em] uppercase">Multi-Mesh Pro</span>
          </div>
        </div>
        <div className="flex items-center gap-6">
          <div className={clsx("flex items-center gap-2 px-3 py-1.5 rounded-full text-[10px] font-bold border uppercase tracking-widest transition-all", status === 'Online' ? "bg-green-500/10 border-green-500/20 text-green-400" : "bg-red-500/10 border-red-500/20 text-red-400")}>
            <Globe className={clsx("w-3 h-3", status === 'Online' && "animate-spin-slow")} />
            {status === 'Online' ? 'Network Online' : 'Network Lost'}
          </div>
          <div className="h-8 w-px bg-gray-800" />
          <div className="flex flex-col items-end">
            <span className="text-xs font-bold text-gray-300">@{username}</span>
            <span className="text-[10px] text-gray-500">UID: {socket.id?.slice(0, 6)}</span>
          </div>
          <button onClick={handleLogout} className="flex items-center gap-2 px-3 py-2 rounded-xl bg-gray-800/50 hover:bg-red-500/10 hover:text-red-400 text-gray-400 transition-all border border-transparent hover:border-red-500/20 group">
            <LogOut className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
            <span className="text-xs font-bold hidden md:block">Sign Out</span>
          </button>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-6 py-8 grid grid-cols-1 lg:grid-cols-12 gap-8">

        {/* LEFT COLUMN: PRIMARY CONTROLS */}
        <div className="lg:col-span-8 space-y-6">

          {/* MESH DISCOVERY PANEL */}
          <div className="bg-[#121826] border border-gray-800 rounded-3xl p-8 shadow-2xl relative z-30 overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10"><Zap className="w-32 h-32 text-blue-500" /></div>
            {!isJoined ? (
              <div className="relative z-10">
                <h2 className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-6 flex items-center gap-3">
                  <Users className="w-5 h-5 text-blue-400" /> Mesh Room Initialization
                </h2>
                
                {roomMode === 'select' ? (
                  // Show Create/Join/Add User buttons
                  <div className="space-y-4">
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      <button 
                        onClick={handleCreateRoom}
                        className="bg-gradient-to-br from-blue-600 to-blue-700 hover:from-blue-500 hover:to-blue-600 text-white font-bold py-4 px-6 rounded-2xl transition-all shadow-xl shadow-blue-600/30 flex flex-col items-center justify-center gap-2 group"
                      >
                        <Zap className="w-5 h-5 group-hover:scale-110 transition-transform" />
                        <span className="text-sm">Create Room</span>
                      </button>
                      
                      <button 
                        onClick={() => setRoomMode('join')}
                        className="bg-gradient-to-br from-purple-600 to-purple-700 hover:from-purple-500 hover:to-purple-600 text-white font-bold py-4 px-6 rounded-2xl transition-all shadow-xl shadow-purple-600/30 flex flex-col items-center justify-center gap-2 group"
                      >
                        <Users className="w-5 h-5 group-hover:scale-110 transition-transform" />
                        <span className="text-sm">Join Room</span>
                      </button>

                      <button 
                        onClick={() => setRoomMode('addUser')}
                        className="bg-gradient-to-br from-emerald-600 to-emerald-700 hover:from-emerald-500 hover:to-emerald-600 text-white font-bold py-4 px-6 rounded-2xl transition-all shadow-xl shadow-emerald-600/30 flex flex-col items-center justify-center gap-2 group"
                      >
                        <UserPlus className="w-5 h-5 group-hover:scale-110 transition-transform" />
                        <span className="text-sm">Add User</span>
                      </button>
                    </div>
                    <p className="text-xs text-gray-500 text-center flex items-center justify-center gap-2"><Info className="w-3 h-3" /> Each room gets a unique 6-character ID.</p>
                  </div>
                ) : roomMode === 'join' ? (
                  // Show join input field
                  <div className="space-y-4">
                    <div className="flex gap-3">
                      <input
                        value={joinRoomInput}
                        onChange={e => setJoinRoomInput(e.target.value.toUpperCase())}
                        onKeyPress={(e) => e.key === 'Enter' && handleJoinRoom()}
                        placeholder="Enter 6-character Room ID (e.g. 'a1b2c3')"
                        className="flex-1 bg-black border border-gray-700 focus:border-purple-500 rounded-2xl px-5 py-3 text-white outline-none placeholder:text-gray-600 font-medium uppercase tracking-wider transition-all"
                        maxLength={6}
                      />
                      <button 
                        onClick={handleJoinRoom}
                        className="bg-purple-600 hover:bg-purple-500 text-white font-bold px-8 py-3 rounded-xl transition-all shadow-xl shadow-purple-600/20 flex items-center gap-2"
                      >
                        <Play className="w-4 h-4 fill-current" /> JOIN
                      </button>
                    </div>
                    <button 
                      onClick={() => {
                        setRoomMode('select');
                        setJoinRoomInput('');
                      }}
                      className="w-full text-xs font-bold text-gray-400 hover:text-gray-300 py-2 transition-colors"
                    >
                      ← Back
                    </button>
                    <p className="text-xs text-gray-500 text-center"><Info className="w-3 h-3 inline mr-1" /> Enter the room ID shared by the creator.</p>
                  </div>
                ) : roomMode === 'addUser' ? (
                  // Add user by searching username (direct handshake)
                  <div className="space-y-4">
                    <p className="text-xs text-gray-400">
                      Search a verified username and send a direct encrypted handshake — no room ID required.
                    </p>
                    <div className="relative group">
                      <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-500 w-5 h-5 group-focus-within:text-blue-500 transition-colors" />
                      <input
                        type="text"
                        placeholder="Search unique username (e.g. alice, bob)"
                        className="w-full bg-black border border-gray-700 rounded-2xl py-4 pl-12 pr-4 text-white outline-none focus:border-blue-500/50 transition-all font-medium"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value.trim().toLowerCase())}
                      />

                      {isSearching && (
                        <div className="absolute right-4 top-1/2 -translate-y-1/2">
                          <Loader2 className="animate-spin w-4 h-4 text-blue-500" />
                        </div>
                      )}

                      <AnimatePresence>
                        {searchQuery.length > 2 && !isSearching && (
                          <motion.div
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: 10 }}
                            className="absolute top-full left-0 right-0 mt-3 bg-[#1A202C] border border-gray-700 rounded-2xl shadow-[0_20px_50px_rgba(0,0,0,0.5)] z-50 overflow-hidden"
                          >
                            {verifiedUser ? (
                              <div
                                className="p-4 flex items-center justify-between hover:bg-gray-800/50 cursor-pointer transition-colors"
                                onClick={() => handleDirectConnect(searchResult || verifiedUser.name)}
                              >
                                <div className="flex items-center gap-4">
                                  <div className="w-10 h-10 rounded-xl bg-green-500/20 text-green-400 flex items-center justify-center border border-green-500/30 font-bold shadow-inner">
                                    {verifiedUser.name[0].toUpperCase()}
                                  </div>
                                  <div>
                                    <span className="font-bold text-gray-200 block">{verifiedUser.name}</span>
                                    <span className="text-[10px] text-green-400 font-mono tracking-tighter flex items-center gap-1">
                                      <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" /> ONLINE
                                    </span>
                                  </div>
                                </div>
                                <button className="text-xs font-black bg-blue-600 hover:bg-blue-500 text-white px-5 py-2.5 rounded-xl shadow-lg transition-all active:scale-95">
                                  CONNECT
                                </button>
                              </div>
                            ) : (
                              <div className="p-6 text-center text-gray-500 text-sm flex flex-col items-center gap-2">
                                <UserX className="w-8 h-8 opacity-20" />
                                No user matches this identifier.
                              </div>
                            )}
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>

                    <button 
                      onClick={() => {
                        setRoomMode('select');
                        setSearchQuery('');
                        setSearchResult(null);
                        setVerifiedUser(null);
                      }}
                      className="w-full text-xs font-bold text-gray-400 hover:text-gray-300 py-2 transition-colors flex items-center justify-center gap-2"
                    >
                      <ArrowLeft className="w-4 h-4" /> Back
                    </button>
                  </div>
                ) : null}
              </div>
            ) : (
              <div className="relative z-10 flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                <div className="space-y-1">
                  <h2 className="text-2xl font-black text-white flex items-center gap-3 italic tracking-tight uppercase">
                    <Globe className="text-blue-500 animate-pulse" /> {roomId}
                  </h2>
                  <div className="flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                    <p className="text-xs font-bold text-blue-400 uppercase tracking-widest">{peers.length} Nodes Connected</p>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <div className="flex -space-x-3 hover:space-x-1 transition-all duration-500">
                    {peers.map((p, i) => (
                      <motion.div
                        key={i}
                        initial={{ x: 20, opacity: 0 }} animate={{ x: 0, opacity: 1 }}
                        title={`${p.username} (${p.status})`}
                        className={clsx("w-12 h-12 rounded-2xl border-4 border-[#121826] flex items-center justify-center text-sm font-black text-white shadow-xl transition-transform hover:scale-110 cursor-pointer",
                          p.status === 'connected' ? "bg-gradient-to-br from-green-500 to-emerald-700" : "bg-gradient-to-br from-yellow-500 to-orange-700")}
                      >
                        {p.username[0].toUpperCase()}
                      </motion.div>
                    ))}
                    {peers.length === 0 && <div className="text-gray-500 text-sm font-bold animate-pulse px-4 border-l border-gray-800">Waiting for peers to join...</div>}
                  </div>
                  <button
                    type="button"
                    onClick={() => setShowAddUserPanel(true)}
                    className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-xs font-bold uppercase tracking-widest text-white shadow-lg shadow-emerald-600/30 transition-all"
                  >
                    <UserPlus className="w-4 h-4" />
                    Add User
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* FILE SELECTION PIPELINE */}
          <div className="relative z-10 group">
            {queueStatus && (
              <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="mb-4 bg-blue-500/10 border border-blue-500/20 p-4 rounded-2xl flex items-center justify-center gap-4 shadow-xl">
                <Loader2 className="animate-spin text-blue-400 w-5 h-5" />
                <span className="text-sm font-black text-blue-400 uppercase tracking-widest">{queueStatus}</span>
              </motion.div>
            )}
            <div className={clsx("transition-all duration-500", isTransferring ? "opacity-50 blur-sm pointer-events-none scale-95" : "opacity-100")}>
              <FilePicker onFilesSelected={startBatchTransfer} disabled={(!isJoined && peers.length === 0) || isTransferring || !encryptionReady} />
            </div>
          </div>

          {/* INTELLIGENCE REPORT DROPDOWN (Entropy, Risk, etc.) */}
          <AnimatePresence>
            {advancedStats && (
              <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mt-4">
                <details className="group bg-[#0B0F14] border border-gray-800 rounded-3xl overflow-hidden transition-all duration-300 open:border-blue-500/30 shadow-xl">
                  <summary className="flex items-center justify-between p-5 cursor-pointer hover:bg-gray-800/50 select-none">
                    <div className="flex items-center gap-3 text-sm font-bold text-gray-400 group-open:text-blue-400 uppercase tracking-widest">
                      <ShieldCheck className="w-5 h-5" /> SmartStream Analysis Report
                    </div>
                    <ChevronDown className="w-5 h-5 text-gray-600 group-open:rotate-180 transition-transform" />
                  </summary>

                  <div className="p-6 pt-0 border-t border-gray-800/50 grid grid-cols-2 md:grid-cols-3 gap-6 text-[11px] font-mono">
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Heuristic Strategy</span>
                      <div className="flex items-center gap-2 text-blue-300 bg-blue-500/10 px-3 py-1.5 rounded-lg border border-blue-500/20 w-max shadow-inner">
                        <Terminal className="w-3.5 h-3.5" /> {advancedStats.algorithm}
                      </div>
                    </div>
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Data Entropy</span>
                      <div className="text-gray-300 text-sm font-bold">{advancedStats.entropy ? advancedStats.entropy.toFixed(4) : 'N/A'} <span className="text-gray-600 text-[10px]">bits/byte</span></div>
                    </div>
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Security Clearance</span>
                      <div className={clsx("font-black text-sm flex items-center gap-1.5 px-3 py-1.5 rounded-lg border w-max shadow-inner",
                        advancedStats.securityStatus === 'Suspicious' ? "text-red-400 bg-red-400/10 border-red-500/20" : "text-green-400 bg-green-400/10 border-green-500/20")}>
                        {advancedStats.securityStatus === 'Suspicious' ? <ShieldAlert className="w-3.5 h-3.5" /> : <Lock className="w-3.5 h-3.5" />}
                        {advancedStats.securityStatus} ({advancedStats.riskScore}%)
                      </div>
                    </div>
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Compression Percentage</span>
                      <div className="text-green-400 text-sm font-black italic">{((1 - advancedStats.compressedSize / advancedStats.originalSize) * 100).toFixed(2)}%</div>
                    </div>
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Transport Payload</span>
                      <div className="text-gray-300 text-sm font-bold">{(advancedStats.compressedSize / 1024).toFixed(2)} <span className="text-gray-600">KB</span></div>
                    </div>
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Integrity Hash</span>
                      <div className="text-gray-500 text-[9px] truncate w-full">0x{Math.random().toString(16).slice(2, 10)}...[Verified]</div>
                    </div>
                  </div>
                </details>
              </motion.div>
            )}
          </AnimatePresence>

          {/* REAL-TIME PERFORMANCE GRID (Bandwidth Efficiency) */}
          <AnimatePresence>
            {transferStats && (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}
                className="grid grid-cols-2 md:grid-cols-4 gap-5"
              >
                <StatCard label="Input Size" value={`${(transferStats.originalSize / 1024 / 1024).toFixed(2)} MB`} icon={Layers} color="text-gray-400" />
                <StatCard label="Bandwidth Efficiency" value={`${(transferStats.finalSize / 1024).toFixed(1)} KB`} icon={Wifi} color="text-blue-400" />
                <StatCard label="Compression" value={`${transferStats.compressionPercent}%`} icon={Zap} color="text-green-400" />
                <StatCard label="Tunnel Speed" value={`${transferStats.speed || 'N/A'} MB/s`} icon={Activity} color="text-yellow-400" />
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* RIGHT COLUMN: REPOSITORY & LOGS */}
        <div className="lg:col-span-4 space-y-6 flex flex-col h-full">

          {/* DOWNLOADS HUB */}
          {receivedFiles.length > 0 && (
            <motion.div
              initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }}
              className="bg-[#121826] border border-gray-800 rounded-[2.5rem] p-6 shadow-2xl overflow-hidden relative"
            >
              <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-blue-500 to-transparent" />
              <h3 className="text-xs font-black text-gray-500 mb-5 flex items-center gap-3 tracking-[0.2em] uppercase">
                <Download className="w-5 h-5 text-green-500" /> Received Hub
              </h3>
              <div className="space-y-3 max-h-64 overflow-y-auto custom-scrollbar pr-2">
                {receivedFiles.map((f, i) => (
                  <motion.div
                    key={i} layout initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                    className="flex justify-between items-center bg-black/40 p-4 rounded-2xl border border-gray-800/50 hover:border-blue-500/30 transition-all group"
                  >
                    <div className="flex flex-col overflow-hidden">
                      <span className="text-sm text-gray-200 truncate w-40 font-bold tracking-tight">{f.name}</span>
                      <span className="text-[9px] text-gray-600 font-mono italic">{new Date().toLocaleTimeString()} • Verified</span>
                    </div>
                    <a
                      href={f.url} download={f.name}
                      className="text-blue-500 hover:text-white bg-blue-500/10 hover:bg-blue-600 p-2.5 rounded-xl transition-all shadow-lg active:scale-90"
                    >
                      <Download className="w-5 h-5" />
                    </a>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}

          {/* SYSTEM LOGS TERMINAL */}
          <div className="bg-black border border-gray-800 rounded-[2.5rem] p-1 flex-1 flex flex-col min-h-[450px] shadow-[0_30px_60px_-12px_rgba(0,0,0,0.8)] overflow-hidden">
            <div className="px-6 py-4 border-b border-gray-800 flex items-center justify-between bg-gray-900/30 rounded-t-[2.4rem]">
              <div className="flex items-center gap-3">
                <Terminal className="w-4 h-4 text-blue-500" />
                <span className="text-[10px] font-black text-gray-500 tracking-[0.2em] uppercase">Security Engine Output</span>
              </div>
              <div className="flex gap-2">
                <div className="w-2.5 h-2.5 rounded-full bg-red-500/20" />
                <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/20" />
                <div className="w-2.5 h-2.5 rounded-full bg-green-500/20 animate-pulse" />
              </div>
            </div>
            <div className="flex-1 p-6 font-mono text-[10px] space-y-2 overflow-y-auto custom-scrollbar text-gray-400 bg-gradient-to-b from-black to-[#05070a]">
              {logs.map((l, i) => (
                <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} className="flex gap-3 items-start group">
                  <span className="text-blue-500 font-black opacity-40 group-hover:opacity-100 transition-opacity">»</span>
                  <span className={clsx("leading-relaxed",
                    l.includes('Error') || l.includes('Block') ? "text-red-400 font-bold" :
                      l.includes('Receiving') || l.includes('Mesh') ? "text-blue-400" :
                        l.includes('Ready') || l.includes('Integrated') ? "text-green-400" : "text-gray-500")
                  }>
                    {l}
                  </span>
                </motion.div>
              ))}
              <div className="animate-pulse text-blue-500 font-black pl-1">_</div>
            </div>
          </div>
        </div>
      </div>

      {/* OVERLAY: GLOBAL PROGRESS MONITOR */}
      <AnimatePresence>
        {isTransferring && (
          <motion.div
            initial={{ y: 50, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 50, opacity: 0 }}
            className="fixed bottom-0 left-0 right-0 bg-[#0B0F14]/90 backdrop-blur-xl border-t border-blue-500/20 p-6 z-50 shadow-[0_-20px_40px_rgba(0,0,0,0.4)]"
          >
            <div className="max-w-4xl mx-auto flex flex-col gap-3">
              <div className="flex justify-between items-center px-1">
                <span className="text-[10px] font-black text-blue-400 animate-pulse flex items-center gap-3 tracking-[0.3em] uppercase">
                  <Activity className="w-4 h-4" /> Multi-Node Synchronization Active
                </span>
                <span className="text-xs font-mono font-black text-gray-400 bg-gray-800/50 px-3 py-1 rounded-lg">{Math.round(progress)}% Complete</span>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* MODAL: INCOMING ENCRYPTED REQUEST */}
      <AnimatePresence>
        {incomingRequest && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-md px-6">
            <motion.div
              initial={{ scale: 0.9, opacity: 0, rotateX: 45 }} animate={{ scale: 1, opacity: 1, rotateX: 0 }} exit={{ scale: 0.9, opacity: 0 }}
              className="bg-[#121826] border border-blue-500/30 p-10 rounded-[3rem] shadow-[0_0_100px_rgba(59,130,246,0.2)] max-w-md w-full text-center relative overflow-hidden"
            >
              <div className="absolute -top-24 -left-24 w-48 h-48 bg-blue-500/10 rounded-full blur-3xl" />
              <div className="absolute -bottom-24 -right-24 w-48 h-48 bg-blue-500/10 rounded-full blur-3xl" />

              <div className="w-20 h-20 bg-blue-500/10 rounded-3xl flex items-center justify-center mx-auto mb-6 border border-blue-500/20 shadow-inner">
                <Bell className="w-10 h-10 text-blue-400 animate-bounce" />
              </div>
              <h3 className="text-2xl font-black text-white mb-3 tracking-tighter">Inbound Handshake</h3>
              <p className="text-gray-400 mb-10 leading-relaxed font-medium">
                {/* @ts-ignore */}
                <strong className="text-blue-400">@{incomingRequest.from}</strong> is requesting a secure P2P tunnel initialization.
              </p>
              <div className="flex gap-4">
                <button
                  onClick={() => setIncomingRequest(null)}
                  className="flex-1 py-4 rounded-2xl bg-gray-800 hover:bg-gray-700 text-gray-300 font-black text-xs uppercase tracking-widest transition-all"
                >
                  Reject
                </button>
                
                {/* ✅ CONNECTED TO THE HANDSHAKE LOGIC */}
                <button
                  onClick={acceptRequest}
                  className="flex-1 py-4 rounded-2xl bg-blue-600 hover:bg-blue-500 text-white font-black text-xs uppercase tracking-widest shadow-xl shadow-blue-600/30 transition-all active:scale-95"
                >
                  Authorize
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: ADD USER WHILE IN ROOM */}
      <AnimatePresence>
        {showAddUserPanel && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[90] flex items-center justify-center bg-black/80 backdrop-blur-md px-6"
          >
            <motion.div
              initial={{ scale: 0.95, y: 20, opacity: 0 }}
              animate={{ scale: 1, y: 0, opacity: 1 }}
              exit={{ scale: 0.95, y: 20, opacity: 0 }}
              className="bg-[#121826] border border-emerald-500/40 p-8 rounded-[2.5rem] shadow-[0_0_80px_rgba(16,185,129,0.3)] max-w-lg w-full relative overflow-hidden"
            >
              <div className="absolute -top-24 -right-24 w-48 h-48 bg-emerald-500/10 rounded-full blur-3xl" />
              <div className="absolute -bottom-24 -left-24 w-48 h-48 bg-emerald-500/10 rounded-full blur-3xl" />

              <div className="flex items-center justify-between mb-6">
                <div>
                  <h3 className="text-xl font-black text-white tracking-tight flex items-center gap-2">
                    <UserPlus className="w-5 h-5 text-emerald-400" /> Add User to Mesh
                  </h3>
                  <p className="text-xs text-gray-400 mt-1">
                    Initiate a direct encrypted handshake with a verified username — no room ID sharing required.
                  </p>
                </div>
                <button
                  onClick={() => setShowAddUserPanel(false)}
                  className="text-xs text-gray-500 hover:text-gray-300 font-bold uppercase tracking-widest"
                >
                  Close
                </button>
              </div>

              <div className="space-y-4">
                <div className="relative group">
                  <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-500 w-5 h-5 group-focus-within:text-emerald-400 transition-colors" />
                  <input
                    type="text"
                    placeholder="Search unique username (e.g. alice, bob)"
                    className="w-full bg-black border border-gray-700 rounded-2xl py-3.5 pl-12 pr-4 text-white outline-none focus:border-emerald-500/60 transition-all font-medium"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value.trim().toLowerCase())}
                  />

                  {isSearching && (
                    <div className="absolute right-4 top-1/2 -translate-y-1/2">
                      <Loader2 className="animate-spin w-4 h-4 text-emerald-400" />
                    </div>
                  )}

                  <AnimatePresence>
                    {searchQuery.length > 2 && !isSearching && (
                      <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: 10 }}
                        className="absolute top-full left-0 right-0 mt-3 bg-[#1A202C] border border-gray-700 rounded-2xl shadow-[0_20px_50px_rgba(0,0,0,0.5)] z-50 overflow-hidden"
                      >
                        {verifiedUser ? (
                          <div
                            className="p-4 flex items-center justify-between hover:bg-gray-800/50 cursor-pointer transition-colors"
                            onClick={() => {
                              handleDirectConnect(searchResult || verifiedUser.name);
                              setShowAddUserPanel(false);
                            }}
                          >
                            <div className="flex items-center gap-4">
                              <div className="w-10 h-10 rounded-xl bg-green-500/20 text-green-400 flex items-center justify-center border border-green-500/30 font-bold shadow-inner">
                                {verifiedUser.name[0].toUpperCase()}
                              </div>
                              <div>
                                <span className="font-bold text-gray-200 block">{verifiedUser.name}</span>
                                <span className="text-[10px] text-green-400 font-mono tracking-tighter flex items-center gap-1">
                                  <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" /> ONLINE
                                </span>
                              </div>
                            </div>
                            <button className="text-xs font-black bg-emerald-600 hover:bg-emerald-500 text-white px-5 py-2.5 rounded-xl shadow-lg transition-all active:scale-95">
                              CONNECT
                            </button>
                          </div>
                        ) : (
                          <div className="p-6 text-center text-gray-500 text-sm flex flex-col items-center gap-2">
                            <UserX className="w-8 h-8 opacity-20" />
                            No user matches this identifier.
                          </div>
                        )}
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>

                <p className="text-[10px] text-gray-500 mt-1">
                  Tip: Usernames are case-insensitive and must match exactly what the receiver used during registration.
                </p>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* PROGRESS TRACKER - Bottom Position */}
      {isTransferring && transferStage !== 'idle' && (
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="fixed bottom-6 left-1/2 -translate-x-1/2 bg-gray-900/90 border border-gray-700/50 p-5 rounded-2xl backdrop-blur z-50 max-w-[85vw]">
          <TransferProgressStages 
            currentStage={transferStage}
            isReceiver={receiverPipelineRef.current !== null}
            fileName={currentFileName}
          />
        </motion.div>
      )}
    </div>
  );
};

// --- SUBSIDIARY COMPONENT: PERFORMANCE CARD ---
const StatCard = ({ label, value, icon: Icon, color }: any) => (
  <div className="bg-[#121826] border border-gray-800 p-6 rounded-3xl flex flex-col justify-between h-32 shadow-xl hover:border-gray-700 transition-all group overflow-hidden relative">
    <div className="absolute top-0 right-0 p-2 opacity-5 group-hover:opacity-10 transition-opacity"><Icon className="w-16 h-16" /></div>
    <div className="flex items-center justify-between mb-3">
      <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest leading-none">{label}</span>
      <div className={clsx("p-2 rounded-lg bg-gray-900/50 shadow-inner", color)}><Icon className="w-4 h-4" /></div>
    </div>
    <span className="text-xl font-black text-gray-100 tracking-tighter tabular-nums">{value}</span>
  </div>
);