import { useEffect, useState, useRef, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { io, Socket } from 'socket.io-client';
import { motion, AnimatePresence } from 'framer-motion';
import { generateKeyPair, exportPublicKey, importPublicKey, deriveSharedKey } from '../lib/crypto';
import { sendFilePipeline, ReceiverPipeline } from '../lib/pipeline';
import { WebRTCManager } from '../lib/webrtc';
import { processFile } from '../lib/compression';
import { getCompressionStats } from '../lib/stats';
import { FilePicker } from './FilePicker';
import { TransferProgressStages, type TransferStage } from './TransferProgressStages';
import {
  Cpu, Wifi, Download, Bell, Lock, Activity, Layers, Zap, Terminal, Signal, Loader2, Users, LogOut, ShieldAlert, Search, UserX, ChevronDown, ShieldCheck, Globe, Info, XCircle, CheckCircle
} from 'lucide-react';
import clsx from 'clsx';

// Type for compression formats supported by DecompressionStream
type CompressionFormat = 'deflate' | 'gzip';

// --- THEME CONFIGURATION ---
const COLORS = {
  bg: '#0B0F14',
  surface: '#121826',
  text: '#E5E7EB',
  accent: '#3B82F6'
};

/**
 * 🛠 HELPER: ROBUST DECOMPRESSION
 * Handles the specific names generated by our heuristic logic.
 */
const decompressBlob = async (blob: Blob, algo: string, fileName: string): Promise<Blob> => {
  try {
    console.log(`[Decompress] STARTING - algo: "${algo}", fileName: "${fileName}", blob size: ${blob.size}`);

    // 1. If logic said "Store", we do NOT decompress
    if (algo.startsWith('Store')) {
      console.log(`[Decompress] Detected Store algo - returning blob as-is`);
      return blob;
    }

    let format: CompressionFormat | null = null;

    // 2. Check Explicit Algorithm Label
    if (algo.includes('Deflate')) {
      format = 'deflate';
      console.log(`[Decompress] Matched "Deflate" - using deflate`);
    }
    else if (algo.includes('Gzip')) {
      format = 'gzip';
      console.log(`[Decompress] Matched "Gzip" - using gzip`);
    }
    // 3. Fallback: Extension
    else if (fileName.endsWith('.gz')) {
      format = 'gzip';
      console.log(`[Decompress] Matched .gz extension - using gzip`);
    }

    if (!format) {
      console.log(`[Decompress] NO FORMAT MATCHED for algo: "${algo}"`);
      return blob;
    }

    console.log(`[Decompress] Using format: ${format}, input size: ${blob.size} bytes`);

    // Get the raw blob data first to verify it's not empty
    const blobBuffer = await blob.arrayBuffer();
    console.log(`[Decompress] Blob buffer size: ${blobBuffer.byteLength} bytes`);

    if (blobBuffer.byteLength === 0) {
      console.error(`[Decompress] ERROR: Received empty blob! Cannot decompress.`);
      return blob;
    }

    try {
      console.log(`[Decompress] Creating DecompressionStream with format: ${format}`);
      const ds = new DecompressionStream(format);
      const decompressedStream = blob.stream().pipeThrough(ds);
      const decompressedBlob = await new Response(decompressedStream).blob();

      console.log(`[Decompress] SUCCESS! Decompressed size: ${decompressedBlob.size} bytes`);

      if (decompressedBlob.size === 0) {
        console.error(`[Decompress] ERROR: Decompression produced empty blob!`);
        return blob;
      }

      return decompressedBlob;
    } catch (decompressError) {
      console.error(`[Decompress] DecompressionStream FAILED:`, decompressError);
      console.log(`[Decompress] Returning original blob as fallback`);
      return blob;
    }
  } catch (error) {
    console.error("[Decompress] CRITICAL ERROR:", error);
    console.error("[Decompress] Algo:", algo, "File:", fileName, "Blob size:", blob.size);
    return blob;
  }
};

const SERVER_URL = import.meta.env.VITE_SERVER_URL || 'https://smartstream-algoquest.onrender.com';
const socket: Socket = io(SERVER_URL, {
  transports: ['websocket', 'polling'],
  reconnectionAttempts: 10,
  reconnectionDelay: 1000
});

export const TransferRoom = () => {
  const navigate = useNavigate();

  // Helper function to generate unique 6-character room ID (lowercase letters + numbers)
  const generateRoomId = (): string => {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    let roomId = '';
    for (let i = 0; i < 6; i++) {
      roomId += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return roomId;
  };

  // --- CORE IDENTITY STATE ---
  const [username] = useState(localStorage.getItem('username') || '');
  const [status, setStatus] = useState('Initializing Systems...');
  const [, setP2pState] = useState<string>('disconnected');

  // --- NETWORKING: ROOMS & DISCOVERY ---
  const [roomId, setRoomId] = useState('');
  const [isJoined, setIsJoined] = useState(false);
  const [roomMode, setRoomMode] = useState<'select' | 'create' | 'join'>('select'); // 'select' = show Create/Join buttons, 'create' = room created, 'join' = joining
  const [joinRoomInput, setJoinRoomInput] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResult, setSearchResult] = useState<string | null>(null);
  const [isSearching, setIsSearching] = useState(false);
  const [verifiedUser, setVerifiedUser] = useState<{ name: string, status: string } | null>(null);

  // Stores request info: { from: 'Alice', key: JsonWebKey, id: 'socket_id_123' }
  const [incomingRequest, setIncomingRequest] = useState<{ from: string, key: JsonWebKey, id: string } | null>(null);

  // --- MESH TOPOLOGY STATE ---
  const [peers, setPeers] = useState<{ id: string, username: string, status: string }[]>([]);
  const peersRef = useRef<Map<string, WebRTCManager>>(new Map());
  const keysRef = useRef<Map<string, CryptoKey>>(new Map());
  const keyPairRef = useRef<CryptoKeyPair | null>(null);
  const receiverPipelineRef = useRef<ReceiverPipeline | null>(null);
  const lastAckRef = useRef<string>('');

  // --- UI & PIPELINE MONITORING ---
  const [isTransferring, setIsTransferring] = useState(false);
  const [encryptionReady, setEncryptionReady] = useState(false);
  const [, setProgress] = useState(0);
  const [logs, setLogs] = useState<string[]>([]);
  const [receivedFiles, setReceivedFiles] = useState<{ name: string, url: string, timestamp: number }[]>([]);
  const [transferStats, setTransferStats] = useState<any>(null);
  const [queueStatus, setQueueStatus] = useState('');
  const [advancedStats, setAdvancedStats] = useState<any>(null);
  const [transferStage, setTransferStage] = useState<TransferStage>('idle');
  const [currentFileName, setCurrentFileName] = useState('');

  // Terminal Logger
  const addLog = (msg: string) => setLogs(prev => [...prev.slice(-19), `${new Date().toLocaleTimeString()} - ${msg}`]);

  // --- TOAST NOTIFICATIONS ---
  const [toasts, setToasts] = useState<{ id: string, type: 'success' | 'error' | 'info', message: string }[]>([]);
  const addToast = (type: 'success' | 'error' | 'info', message: string) => {
    const id = Math.random().toString(36).substring(7);
    setToasts(prev => [...prev, { id, type, message }]);
    setTimeout(() => setToasts(prev => prev.filter(t => t.id !== id)), 4000);
  };

  // --- BACK BUTTON PROTECTION ---
  // Active on Mount: Protects against accidental back navigation even if not yet in a room
  useEffect(() => {
    const handlePopState = (event: PopStateEvent) => {
      event.preventDefault();
      // Push state back to prevent navigation
      window.history.pushState(null, '', window.location.pathname);

      const confirmLogout = window.confirm("Are you sure you want to log out? This will disconnect you from the mesh.");
      if (confirmLogout) {
        handleLogout();
      }
    };

    // Push initial state
    window.history.pushState(null, '', window.location.pathname);
    window.addEventListener('popstate', handlePopState);

    return () => {
      window.removeEventListener('popstate', handlePopState);
    };
  }, []);

  // =========================================
  // 1. CONNECTION FACTORY (WebRTC HANDSHAKE)
  // =========================================
  const createPeerConnection = useCallback((targetId: string, isInitiator: boolean) => {
    console.log(`[createPeerConnection] Creating ${isInitiator ? 'INITIATOR' : 'NON-INITIATOR'} connection to ${targetId}`);

    if (peersRef.current.has(targetId)) {
      console.log(`[createPeerConnection] Connection already exists for ${targetId}`);
      return peersRef.current.get(targetId)!;
    }

    const manager = new WebRTCManager(socket, targetId,
      (data) => handleIncomingData(data, targetId),
      (state) => {
        console.log(`[WebRTC] State change for ${targetId}: ${state}`);
        setPeers(prev => prev.map(p => p.id === targetId ? { ...p, status: state } : p));
        if (state === 'connected') {
          setP2pState('connected');
          if (keyPairRef.current) {
            exportPublicKey(keyPairRef.current.publicKey).then(k => {
              console.log(`[WebRTC] Sending pub-key to ${targetId}`);
              socket.emit('signal', { target: targetId, payload: { type: 'pub-key', key: k } });
            });
          }
        } else if (state === 'failed' || state === 'closed') {
          console.log(`[WebRTC] Closing connection to ${targetId}`);
          peersRef.current.delete(targetId);
          keysRef.current.delete(targetId);
        }
      }
    );

    console.log(`[createPeerConnection] Initializing connection, isInitiator=${isInitiator}`);
    manager.initConnection(isInitiator);
    peersRef.current.set(targetId, manager);
    console.log(`[createPeerConnection] Connection created and stored, total managers: ${peersRef.current.size}`);
    return manager;
  }, [socket, username]);

  // =========================================
  // 2. INITIALIZATION & SOCKET BUS
  // =========================================
  useEffect(() => {
    if (!username) { navigate('/auth'); return; }

    generateKeyPair().then(keys => {
      keyPairRef.current = keys;
      addLog("Local Identity ECDH Keys Generated");
    });

    socket.emit('register-user', username);
    setStatus('Online');

    socket.on('connect', () => { setStatus('Online'); socket.emit('register-user', username); });
    socket.on('disconnect', () => { setStatus('Offline'); setEncryptionReady(false); });

    // NEW: Handle room-exists check response
    socket.on('room-exists', ({ roomId, exists }) => {
      if (exists) {
        console.log(`[Room] Room ${roomId} exists. Joining...`);
        socket.emit('join-room', roomId, username);
        setRoomId(roomId);
        setRoomMode('join');
        setIsJoined(true);
        addLog(`Joined Private Mesh Room: ${roomId}`);
      } else {
        alert("Room not found! Please check the ID.");
      }
    });

    // NEW: Handle Room Users Sync (Remove stale users)
    socket.on('room-users-sync', (users: { id: string, username: string }[]) => {
      setPeers(prev => {
        const validIds = new Set(users.map(u => u.id));
        // Only keep peers that are in the server's list
        return prev.filter(p => validIds.has(p.id));
      });
    });

    socket.on('user-status', (data: any) => {
      setIsSearching(false);
      if (data.status === 'online') {
        setSearchResult(data.username);
        setVerifiedUser({ name: data.username, status: 'Online' });
      } else {
        setSearchResult(null);
        setVerifiedUser(null);
      }
    });

    socket.on('signal', async ({ sender, payload }) => {
      let manager = peersRef.current.get(sender);

      if (!manager) {
        setPeers(prev => prev.find(p => p.id === sender) ? prev : [...prev, { id: sender, username: `Guest_${sender.slice(0, 4)}`, status: 'Connecting...' }]);
        manager = createPeerConnection(sender, false);
        // Ensure manager is properly initialized before handling signal
        if (!manager) {
          console.error(`Failed to create peer connection for ${sender}`);
          return;
        }
      }

      if (manager) {
        await manager.handleSignal(payload);
      }

      // ✅ CAPTURE SENDER ID HERE
      if (payload.type === 'conn-request') {
        setIncomingRequest({
          from: payload.username || sender,
          key: payload.key,
          id: sender // Store the Socket ID to reply later
        });
      }

      if (payload.type === 'pub-key') {
        try {
          const foreignKey = await importPublicKey(payload.key);
          if (keyPairRef.current) {
            const shared = await deriveSharedKey(keyPairRef.current.privateKey, foreignKey);
            keysRef.current.set(sender, shared);
            addLog(`🔐 AES-256 secure tunnel synced with ${sender.slice(0, 4)}`);
            setEncryptionReady(true);
            setPeers(prev => prev.map(p => p.id === sender ? { ...p, status: 'connected' } : p));
          }
        } catch (e) { console.error("Identity Handshake Failed:", e); }
      }
    });

    socket.on('user-joined', ({ id, username }) => {
      console.log(`[Socket] User joined: ${username} (${id})`);
      addLog(`${username} entered the mesh.`);
      setPeers(prev => prev.find(p => p.id === id) ? prev : [...prev, { id, username, status: 'Connecting...' }]);
      const manager = createPeerConnection(id, false);
      if (!manager) {
        console.error(`Failed to create peer connection for new user ${id}`);
      }
    });

    socket.on('existing-users', (users) => {
      console.log(`[Socket] Existing users received: ${users.length} users`);
      users.forEach((u: any) => {
        console.log(`[Socket] Creating initiator connection to ${u.username} (${u.id})`);
        setPeers(prev => prev.find(p => p.id === u.id) ? prev : [...prev, { id: u.id, username: u.username, status: 'Connecting...' }]);
        const manager = createPeerConnection(u.id, true);
        if (!manager) {
          console.error(`Failed to create peer connection for existing user ${u.id}`);
        }
      });
    });

    socket.on('user-left', (id) => {
      addLog(`User disconnected.`);
      peersRef.current.get(id)?.close();
      peersRef.current.delete(id);
      keysRef.current.delete(id);
      setPeers(prev => prev.filter(p => p.id !== id));
      if (peersRef.current.size === 0) setEncryptionReady(false);
    });

    return () => {
      socket.off('signal');
      socket.off('user-joined');
      socket.off('existing-users');
      socket.off('user-left');
      socket.off('room-exists');
      socket.off('room-users-sync'); // Clean up
      socket.off('user-status');
      socket.off('connect');
      socket.off('disconnect');
    };
  }, [username, navigate, createPeerConnection]);

  // --- SYNC: KEEP ROOM STATE FRESH ---
  useEffect(() => {
    if (!isJoined || !roomId) return;
    const interval = setInterval(() => {
      socket.emit('sync-room-users', roomId);
    }, 5000); // 5 seconds
    return () => clearInterval(interval);
  }, [isJoined, roomId]);

  // --- HIGH-SPEED TURBO LAYER ---
  useEffect(() => {
    const peerCount = peers.length;
    if (peerCount === 1) {
      const manager = peersRef.current.values().next().value;
      if (manager && typeof manager.enableTurboMode === 'function') {
        manager.enableTurboMode();
      }
    } else {
      peersRef.current.forEach(manager => {
        if (typeof manager.disableTurboMode === 'function') {
          manager.disableTurboMode();
        }
      });
    }
  }, [peers]);

  // =========================================
  // 4. USER INTERACTION HANDLERS
  // =========================================
  const handleCreateRoom = () => {
    const newRoomId = generateRoomId();
    setRoomId(newRoomId);
    setRoomMode('create');
    console.log(`[Room] Created new room with ID: ${newRoomId}`);
    socket.emit('join-room', newRoomId, username);
    setIsJoined(true);
    addLog(`Created Private Mesh Room: ${newRoomId}`);
  };

  const handleJoinRoom = () => {
    const idToJoin = joinRoomInput.trim().toLowerCase();
    if (!idToJoin) return alert("Please enter a Room ID");
    if (idToJoin.length !== 6) return alert("Room ID must be exactly 6 characters");

    // VALIDATION: Check if room exists before joining
    console.log(`[Room] Checking existence of room: ${idToJoin}`);
    socket.emit('check-room', idToJoin);
  };

  const handleLeaveRoom = () => {
    if (!isJoined) return;

    console.log(`[Room] Leaving room ${roomId}`);
    socket.emit('leave-room', roomId);

    // Close all connections
    peersRef.current.forEach(p => p.close());
    peersRef.current.clear();
    keysRef.current.clear();
    setPeers([]);

    // Reset State
    setIsJoined(false);
    setRoomId('');
    setRoomMode('select');
    setReceivedFiles([]);
    setLogs(prev => [...prev, `${new Date().toLocaleTimeString()} - Left the room.`]);
    setEncryptionReady(false);
  };

  const handleDirectConnect = (targetUsername: string) => {
    if (!keyPairRef.current) return;
    exportPublicKey(keyPairRef.current.publicKey).then(key => {
      socket.emit('signal', { target: targetUsername, payload: { type: 'conn-request', key, username } });
    });
    addLog(`Broadcasting Direct Connection Request...`);
  };

  // ✅ COMPLETE HANDSHAKE LOGIC
  const acceptRequest = async () => {
    if (!incomingRequest || !keyPairRef.current) return;

    try {
      const { id: senderId, key: foreignKeyJson, from } = incomingRequest;
      addLog(`🔐 Establishing secure tunnel with ${from}...`);

      // 1. Import their key
      const foreignKey = await importPublicKey(foreignKeyJson);

      // 2. Derive shared secret
      const sharedKey = await deriveSharedKey(keyPairRef.current.privateKey, foreignKey);

      // 3. Save key mapped to their Socket ID
      keysRef.current.set(senderId, sharedKey);

      // 4. Send OUR public key back
      const myPublicKey = await exportPublicKey(keyPairRef.current.publicKey);
      socket.emit('signal', {
        target: senderId,
        payload: { type: 'pub-key', key: myPublicKey, username }
      });

      // 5. Update UI
      setEncryptionReady(true);
      setPeers(prev => {
        if (prev.find(p => p.id === senderId)) return prev.map(p => p.id === senderId ? { ...p, status: 'connected' } : p);
        return [...prev, { id: senderId, username: from, status: 'connected' }];
      });

      addLog(`✅ Secure Connection Established`);
    } catch (e) {
      console.error("Handshake failed", e);
      addLog("❌ Handshake Failed");
    }

    setIncomingRequest(null);
  };

  const handleLogout = () => {
    localStorage.clear();
    socket.disconnect();
    peersRef.current.forEach(p => p.close());
    navigate('/auth');
  };

  // =========================================
  // 5. RECEIVER ENGINE (INBOUND DATA PROCESSING)
  // =========================================
  const handleIncomingData = async (data: ArrayBuffer, senderId: string) => {
    try {
      const text = new TextDecoder().decode(data);
      if (text.trim().startsWith('{')) {
        const msg = JSON.parse(text);

        if (msg.type === 'file-start') {
          console.log(`[Receiver] Received file-start metadata:`, msg);
          setIsTransferring(true);
          setCurrentFileName(msg.name);
          setTransferStage('transferred');
          addLog(`⬇️ Receiving: ${msg.name}`);
          setProgress(0);
          const sharedKey = keysRef.current.get(senderId);
          if (sharedKey) {
            receiverPipelineRef.current = new ReceiverPipeline(sharedKey, msg.algo, async (blob, stats) => {
              setTransferStage('decrypting');
              setQueueStatus("Decrypting & Reassembling...");

              try {
                console.log(`[Receiver] Received blob - size: ${blob.size}, algo: ${msg.algo}, name: ${msg.name}`);

                // 1. Verify received blob is not empty
                if (blob.size === 0) {
                  console.error(`[Receiver] ERROR: Received empty blob! Cannot process file.`);
                  addLog(`❌ Received corrupted file (empty blob)`);
                  setIsTransferring(false);
                  setQueueStatus('');
                  return;
                }

                setTransferStage('decrypted');

                // 2. Decompress the received (decrypted) blob
                setTransferStage('decompressing');
                const decompressedBlob = await decompressBlob(blob, msg.algo, msg.name);
                setTransferStage('decompressed');
                console.log(`[Receiver] After decompression - size: ${decompressedBlob.size}`);

                // 3. Verify decompression didn't return empty blob
                if (decompressedBlob.size === 0) {
                  console.error(`[Receiver] ERROR: Decompression resulted in empty blob!`);
                  addLog(`❌ File decompression failed - corrupted data`);
                  setIsTransferring(false);
                  setQueueStatus('');
                  return;
                }

                // 4. Get original file data as bytes to verify integrity
                const arrayBuffer = await decompressedBlob.arrayBuffer();
                const uint8array = new Uint8Array(arrayBuffer);
                console.log(`[Receiver] Decompressed data verified - ${uint8array.length} bytes`);

                // 5. MIME-TYPE ENFORCEMENT - Set correct MIME type based on file extension
                const lowerName = msg.name.toLowerCase();
                let finalMime = 'application/octet-stream';

                if (lowerName.endsWith('.pdf')) {
                  finalMime = 'application/pdf';
                  console.log(`[Receiver] Detected PDF file - MIME type: ${finalMime}`);
                } else if (lowerName.endsWith('.ipynb')) {
                  finalMime = 'application/x-ipynb+json';
                } else if (lowerName.endsWith('.json')) {
                  finalMime = 'application/json';
                } else if (lowerName.endsWith('.txt')) {
                  finalMime = 'text/plain';
                } else if (lowerName.endsWith('.png')) {
                  finalMime = 'image/png';
                } else if (lowerName.endsWith('.jpg') || lowerName.endsWith('.jpeg')) {
                  finalMime = 'image/jpeg';
                } else if (lowerName.endsWith('.zip')) {
                  finalMime = 'application/zip';
                }

                const correctedBlob = new Blob([uint8array], { type: finalMime });
                console.log(`[Receiver] Final blob created - size: ${correctedBlob.size}, mime: ${finalMime}`);

                // 6. Extension Cleanup - Remove compression extensions
                const finalName = msg.name.replace(/\.gz$/, "").replace(/\.br$/, "").replace(/\.deflate$/, "");
                const url = URL.createObjectURL(correctedBlob);

                // NEW: Add timestamp
                setReceivedFiles(prev => [{ name: finalName, url, timestamp: Date.now() }, ...prev]);
                setTransferStage('complete');
                console.log(`[Receiver] File ready for download: ${finalName}`);

                // 7. Update Stats with compression percentage
                // Use msg.originalSize (sent by sender) as the original file size
                // blob.size is the compressed (but decrypted) file size
                const senderOriginalSize = msg.originalSize || correctedBlob.size;
                const receiverStats = getCompressionStats(senderOriginalSize, blob.size);
                setTransferStats({
                  ...stats,
                  originalSize: senderOriginalSize, // Original file size from sender
                  finalSize: blob.size,              // Size after decryption (compressed)
                  compressionPercent: receiverStats.compressionPercent,
                  compressionRatio: receiverStats.compressionRatio
                });

                addLog(`✅ File Integrated: ${finalName}`);
                setProgress(100);
                setIsTransferring(false);
                setQueueStatus('');

                // 8. Send acknowledgment
                const ackMsg = JSON.stringify({ type: 'file-ack', name: msg.name });
                const ackBuffer = new TextEncoder().encode(ackMsg);
                peersRef.current.get(senderId)?.sendData(ackBuffer.buffer as ArrayBuffer);
              } catch (error) {
                console.error('[Receiver] Error processing file:', error);
                addLog(`❌ File processing failed: ${error}`);
                setIsTransferring(false);
                setQueueStatus('');
              }
            });
          }
        }
        else if (msg.type === 'file-end') {
          setTimeout(() => receiverPipelineRef.current?.finish(), 250);
        }
        else if (msg.type === 'file-ack') {
          lastAckRef.current = msg.name;
        }
        return;
      }
    } catch (e) {
      console.warn("Pipeline metadata parsing failed, treating as binary chunk.");
    }

    if (receiverPipelineRef.current) {
      receiverPipelineRef.current.processChunk(data);
      setProgress(p => (p >= 98 ? 98 : p + 0.5));
    }
  };

  // =========================================
  // 6. SENDER ENGINE (SEQUENTIAL BROADCAST)
  // =========================================
  const startBatchTransfer = async (files: File[]) => {
    if (peersRef.current.size === 0) return addToast('error', "Mesh Network Empty. Join a room first.");

    setIsTransferring(true);
    const encoder = new TextEncoder();

    // DYNAMIC BUFFER ALLOCATION (SAFE MODE + TURBO SUPPORT)
    // Base 1MB Limit per channel. Total 4MB in Turbo Mode (4 channels). safe.
    const bufferLimit = 1024 * 1024;
    const bufferThreshold = 64 * 1024;

    peersRef.current.forEach(manager => {
      // @ts-ignore - method added in webrtc.ts
      if (typeof manager.setBufferParams === 'function') {
        manager.setBufferParams(bufferLimit, bufferThreshold);
      }
    });

    try {
      for (let i = 0; i < files.length; i++) {
        const originalFile = files[i];
        setCurrentFileName(originalFile.name);
        setTransferStage('algo-selected');
        setQueueStatus(`Pre-Transfer Security Scan...`);

        // 1. Process File (Forced Compression)
        setTransferStage('compressing');
        const { file: processedData, meta } = await processFile(originalFile);
        setTransferStage('compressed');
        // IMPORTANT: Always use the algorithm that was actually used for compression (meta.algorithm)
        // Do NOT override with analyzeFile recommendation, as that could cause mismatch between
        // what was actually compressed vs what we tell the receiver to decompress with
        const algoName = meta.algorithm;

        console.log(`[Sender] File: ${originalFile.name}`);
        console.log(`[Sender] Meta algorithm from processFile: ${meta.algorithm}`);
        console.log(`[Sender] Final algorithm to use: ${algoName}`);
        console.log(`[Sender] Original size: ${meta.originalSize}, Compressed size: ${meta.compressedSize}`);

        // 2. Set Stats
        setAdvancedStats(meta);

        // 3. Security Block
        if (meta.securityStatus === 'Suspicious') {
          addToast('error', `🚫 Blocked: ${originalFile.name} (Risk: ${meta.riskScore}%)`);
          addLog(`🚫 Blocked potentially harmful file: ${originalFile.name}`);
          continue;
        }

        addLog(`🤖 Intelligence: Applied ${algoName} Strategy`);

        const activePeers = Array.from(peersRef.current.entries());
        let peerCount = 1;

        for (const [peerId, manager] of activePeers) {
          const sharedKey = keysRef.current.get(peerId);
          if (!sharedKey || !manager.dataChannel || manager.dataChannel.readyState !== 'open') continue;

          setQueueStatus(`Mesh Broadcast: Target ${peerCount}/${activePeers.length}...`);
          setProgress(0);

          // 4. Send Metadata (with original file size for compression percentage calculation)
          setTransferStage('encrypting');
          const metaObj = { type: 'file-start', name: originalFile.name, algo: algoName, originalSize: meta.originalSize };
          console.log(`[Sender] Sending file-start metadata:`, metaObj);
          const startMeta = encoder.encode(JSON.stringify(metaObj));
          await manager.sendData(startMeta.buffer as ArrayBuffer);
          setTransferStage('encrypted');

          // 5. Send Binary Pipeline
          setTransferStage('transferring');
          const transferResult = await sendFilePipeline(processedData as any, sharedKey, algoName, async (chunk) => {
            await manager.sendData(chunk);
            setProgress(p => (p >= 98 ? 98 : p + 0.5));
          });
          setTransferStage('transferred');

          // 6. Update Stats for Sender (Using unified compression stats utility)
          const stats = getCompressionStats(meta.originalSize, meta.compressedSize);
          setTransferStats({
            originalSize: stats.originalSize,
            finalSize: stats.compressedSize,
            speed: transferResult.speed,
            compressionPercent: stats.compressionPercent,
            compressionRatio: stats.compressionRatio
          });

          // Backpressure
          // @ts-ignore
          while (manager.dataChannel?.bufferedAmount > 0) await new Promise(r => setTimeout(r, 100));

          // 7. Send Metadata (End)
          const endMeta = encoder.encode(JSON.stringify({ type: 'file-end', name: originalFile.name }));
          await manager.sendData(endMeta.buffer as ArrayBuffer);

          addLog(`Verifying integrity with Peer ${peerCount}...`);
          await new Promise<void>(resolve => {
            const check = setInterval(() => {
              if (lastAckRef.current === originalFile.name) { clearInterval(check); resolve(); }
            }, 150);
            setTimeout(() => { clearInterval(check); resolve(); }, 10000);
          });

          lastAckRef.current = '';
          peerCount++;
        }

        addLog(`✅ Mesh Broadcast Complete: "${originalFile.name}"`);
        setProgress(100);
      }
      setQueueStatus('');
      addLog("Pipeline Empty - Batch Finished");
    } catch (e) {
      console.error(e);
      addLog("❌ Pipeline Error - Transfer Aborted");
    } finally {
      setIsTransferring(false);
      setProgress(0);
    }
  };

  // =========================================
  // 7. UI RENDER ENGINE
  // =========================================
  return (
    <div className="min-h-screen font-sans selection:bg-blue-500/30" style={{ backgroundColor: COLORS.bg, color: COLORS.text }}>

      {/* GLOBAL NAVBAR */}
      <nav className="sticky top-0 z-50 border-b border-gray-800 bg-[#0B0F14]/80 backdrop-blur-md px-6 h-16 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-blue-600 flex items-center justify-center shadow-lg shadow-blue-900/50">
            <Cpu className="text-white w-5 h-5" />
          </div>
          <div className="flex flex-col">
            <span className="font-bold text-xl tracking-tight text-white leading-tight">SmartStream</span>
            {/* <span className="text-blue-500 text-[10px] font-bold tracking-[0.2em] uppercase">Multi-Mesh Pro</span> */}
          </div>
        </div>
        <div className="flex items-center gap-6">
          <div className={clsx("flex items-center gap-2 px-3 py-1.5 rounded-full text-[10px] font-bold border uppercase tracking-widest transition-all", status === 'Online' ? "bg-green-500/10 border-green-500/20 text-green-400" : "bg-red-500/10 border-red-500/20 text-red-400")}>
            <Globe className={clsx("w-3 h-3", status === 'Online' && "animate-spin-slow")} />
            {status === 'Online' ? 'Network Online' : 'Network Lost'}
          </div>
          <div className="h-8 w-px bg-gray-800" />
          <div className="flex flex-col items-end">
            <span className="text-xs font-bold text-gray-300">@{username}</span>
            <span className="text-[10px] text-gray-500">UID: {socket.id?.slice(0, 6)}</span>
          </div>
          <button onClick={handleLogout} className="flex items-center gap-2 px-3 py-2 rounded-xl bg-gray-800/50 hover:bg-red-500/10 hover:text-red-400 text-gray-400 transition-all border border-transparent hover:border-red-500/20 group">
            <LogOut className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
            <span className="text-xs font-bold hidden md:block">Sign Out</span>
          </button>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-6 py-8 grid grid-cols-1 lg:grid-cols-12 gap-8">

        {/* LEFT COLUMN: PRIMARY CONTROLS */}
        <div className="lg:col-span-8 space-y-6">

          {/* MESH DISCOVERY PANEL - 3D STYLE */}
          <div className="bg-gradient-to-b from-[#1a1f2e] to-[#121826] border border-black/50 rounded-[2rem] p-8 shadow-[0_20px_50px_-12px_rgba(0,0,0,0.7)] relative z-30 overflow-hidden group hover:shadow-[0_30px_60px_-12px_rgba(0,0,0,0.8)] transition-all duration-500">
            {/* Inner Top Highlight for 3D effect */}
            <div className="absolute inset-x-0 top-0 h-px bg-white/10" />

            <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity duration-500 transform group-hover:scale-110"><Zap className="w-40 h-40 text-blue-500 blur-sm" /></div>

            {!isJoined ? (
              <div className="relative z-10">
                <h2 className="text-sm font-black text-gray-400 uppercase tracking-[0.2em] mb-8 flex items-center gap-3 border-b border-gray-800 pb-4">
                  <Users className="w-5 h-5 text-blue-500" /> Mesh Room Initialization
                </h2>

                {roomMode === 'select' ? (
                  // Show Create/Join buttons
                  <div className="space-y-6">
                    <div className="grid grid-cols-2 gap-6">
                      <button
                        onClick={handleCreateRoom}
                        className="bg-[#1A202C] hover:bg-[#232936] text-white font-bold py-6 px-6 rounded-2xl transition-all shadow-lg border border-gray-700/50 hover:border-blue-500/50 flex flex-col items-center justify-center gap-3 group relative overflow-hidden"
                      >
                        <div className="absolute inset-0 bg-blue-500/5 opacity-0 group-hover:opacity-100 transition-opacity" />
                        <div className="p-3 rounded-full bg-blue-500/10 text-blue-400 group-hover:scale-110 transition-transform"><Zap className="w-6 h-6" /></div>
                        <span className="text-sm font-black tracking-wide">CREATE MESH</span>
                      </button>

                      <button
                        onClick={() => setRoomMode('join')}
                        className="bg-[#1A202C] hover:bg-[#232936] text-white font-bold py-6 px-6 rounded-2xl transition-all shadow-lg border border-gray-700/50 hover:border-purple-500/50 flex flex-col items-center justify-center gap-3 group relative overflow-hidden"
                      >
                        <div className="absolute inset-0 bg-purple-500/5 opacity-0 group-hover:opacity-100 transition-opacity" />
                        <div className="p-3 rounded-full bg-purple-500/10 text-purple-400 group-hover:scale-110 transition-transform"><Users className="w-6 h-6" /></div>
                        <span className="text-sm font-black tracking-wide">JOIN MESH</span>
                      </button>
                    </div>
                    <p className="text-[10px] text-gray-500 text-center flex items-center justify-center gap-2 font-mono uppercase tracking-widest"><Info className="w-3 h-3" /> Secure P2P Enclave Generation</p>
                  </div>
                ) : roomMode === 'join' ? (
                  // Show join input field
                  <div className="space-y-6">
                    <div className="flex gap-4">
                      <input
                        value={joinRoomInput}
                        onChange={e => setJoinRoomInput(e.target.value.toUpperCase())}
                        onKeyPress={(e) => e.key === 'Enter' && handleJoinRoom()}
                        placeholder="ROOM ID"
                        className="flex-1 bg-black/50 border border-gray-700 focus:border-purple-500 rounded-2xl px-6 py-4 text-white outline-none placeholder:text-gray-700 font-black text-xl uppercase tracking-[0.2em] transition-all shadow-inner"
                        maxLength={6}
                      />
                      <button
                        onClick={handleJoinRoom}
                        className="bg-purple-600 hover:bg-purple-500 text-white font-black px-8 py-3 rounded-2xl transition-all shadow-lg shadow-purple-900/40 flex items-center gap-2 active:translate-y-1"
                      >
                        ENTER
                      </button>
                    </div>
                    <button
                      onClick={() => {
                        setRoomMode('select');
                        setJoinRoomInput('');
                      }}
                      className="w-full text-xs font-bold text-gray-500 hover:text-gray-300 py-2 transition-colors uppercase tracking-widest"
                    >
                      ← Abort Connection
                    </button>
                  </div>
                ) : null}
              </div>
            ) : (
              <div className="relative z-10 flex items-center justify-between">
                <div className="space-y-2">
                  <h2 className="text-3xl font-black text-white flex items-center gap-4 tracking-tighter uppercase relative">
                    <span className="text-gray-700 select-none">#</span> {roomId}
                    <div className="absolute -top-3 -right-3 w-2 h-2 rounded-full bg-green-500 shadow-[0_0_10px_#22c55e]" />
                  </h2>
                  <div className="flex items-center gap-2">
                    <span className="px-2 py-0.5 rounded bg-blue-500/10 border border-blue-500/20 text-[10px] font-bold text-blue-400 uppercase tracking-widest">
                      {peers.length} Nodes Active
                    </span>
                  </div>
                </div>
                {/* NEW: Leave Room Button */}
                {isJoined && (
                  <button
                    onClick={handleLeaveRoom}
                    className="flex items-center gap-2 px-5 py-3 bg-red-500/5 hover:bg-red-500/10 text-red-500/80 hover:text-red-400 rounded-xl border border-red-500/10 transition-all text-[10px] font-black uppercase tracking-widest"
                  >
                    <LogOut className="w-3 h-3" /> Disconnect
                  </button>
                )}
                <div className="flex -space-x-4 hover:space-x-1 transition-all duration-500 pl-4">
                  {peers.map((p, i) => (
                    <motion.div
                      key={i}
                      initial={{ x: 20, opacity: 0 }} animate={{ x: 0, opacity: 1 }}
                      title={`${p.username} (${p.status})`}
                      className={clsx("w-14 h-14 rounded-2xl border-4 border-[#121826] flex items-center justify-center text-lg font-black text-white shadow-2xl transition-transform hover:scale-110 cursor-pointer relative z-10",
                        p.status === 'connected' ? "bg-gradient-to-br from-green-500 to-emerald-700 shadow-green-900/20" : "bg-gradient-to-br from-yellow-500 to-orange-700")}
                    >
                      {p.username[0].toUpperCase()}
                    </motion.div>
                  ))}
                  {peers.length === 0 && <div className="text-gray-600 text-[10px] font-bold animate-pulse px-4 border-l border-gray-800 flex items-center h-14 uppercase tracking-widest">Awaiting Nodes...</div>}
                </div>
              </div>
            )}
          </div>

          {/* DIRECT SEARCH FALLBACK (VISIBLE WHEN NOT IN ROOM) */}
          {!isJoined && (
            <div className="hidden bg-gradient-to-b from-[#1a1f2e] to-[#121826] border border-black/50 rounded-[2rem] p-6 shadow-xl relative z-20">
              <div className="absolute inset-x-0 top-0 h-px bg-white/5" />
              <h2 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-4 flex items-center gap-3"><Signal className="w-4 h-4 text-blue-400" /> Direct Handshake</h2>
              <div className="relative group">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-500 w-5 h-5 group-focus-within:text-blue-500 transition-colors" />
                <input
                  type="text" placeholder="Search unique username for 1-to-1 tunnel..."
                  className="w-full bg-black/60 border border-gray-700/50 rounded-2xl py-4 pl-12 pr-4 text-white outline-none focus:border-blue-500/50 transition-all font-medium placeholder:text-gray-700"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value.trim().toLowerCase())}
                />

                {isSearching && (
                  <div className="absolute right-4 top-1/2 -translate-y-1/2"><Loader2 className="animate-spin w-4 h-4 text-blue-500" /></div>
                )}

                <AnimatePresence>
                  {searchQuery.length > 2 && !isSearching && (
                    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="absolute top-full left-0 right-0 mt-3 bg-[#1A202C] border border-gray-700 rounded-2xl shadow-[0_20px_50px_rgba(0,0,0,0.5)] z-50 overflow-hidden">
                      {verifiedUser ? (
                        <div className="p-4 flex items-center justify-between hover:bg-gray-800/50 cursor-pointer transition-colors" onClick={() => handleDirectConnect(searchResult!)}>
                          <div className="flex items-center gap-4">
                            <div className="w-10 h-10 rounded-xl bg-green-500/20 text-green-400 flex items-center justify-center border border-green-500/30 font-bold shadow-inner">{verifiedUser.name[0].toUpperCase()}</div>
                            <div><span className="font-bold text-gray-200 block">{verifiedUser.name}</span><span className="text-[10px] text-green-400 font-mono tracking-tighter flex items-center gap-1"><span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" /> ONLINE</span></div>
                          </div>
                          <button className="text-xs font-black bg-blue-600 hover:bg-blue-500 text-white px-5 py-2.5 rounded-xl shadow-lg transition-all active:scale-95">CONNECT</button>
                        </div>
                      ) : (
                        <div className="p-6 text-center text-gray-500 text-sm flex flex-col items-center gap-2"><UserX className="w-8 h-8 opacity-20" /> No user matches this identifier.</div>
                      )}
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>
          )}

          {/* FILE SELECTION PIPELINE */}
          <div className="relative z-10 group">
            {queueStatus && (
              <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="mb-4 bg-blue-500/10 border border-blue-500/20 p-4 rounded-2xl flex items-center justify-center gap-4 shadow-xl backdrop-blur-md">
                <Loader2 className="animate-spin text-blue-400 w-5 h-5" />
                <span className="text-sm font-black text-blue-400 uppercase tracking-widest">{queueStatus}</span>
              </motion.div>
            )}
            <div className={clsx("transition-all duration-500", isTransferring ? "opacity-50 blur-sm pointer-events-none scale-95" : "opacity-100")}>
              <FilePicker onFilesSelected={startBatchTransfer} disabled={(!isJoined && peers.length === 0) || isTransferring || !encryptionReady} />
            </div>
          </div>

          {/* INTELLIGENCE REPORT DROPDOWN (Entropy, Risk, etc.) */}
          <AnimatePresence>
            {advancedStats && (
              <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mt-4">
                <details className="group bg-[#0B0F14] border border-gray-800 rounded-3xl overflow-hidden transition-all duration-300 open:border-blue-500/30 shadow-xl">
                  <summary className="flex items-center justify-between p-5 cursor-pointer hover:bg-gray-800/50 select-none">
                    <div className="flex items-center gap-3 text-sm font-bold text-gray-400 group-open:text-blue-400 uppercase tracking-widest">
                      <ShieldCheck className="w-5 h-5" /> SmartStream Analysis Report
                    </div>
                    <ChevronDown className="w-5 h-5 text-gray-600 group-open:rotate-180 transition-transform" />
                  </summary>

                  <div className="p-6 pt-0 border-t border-gray-800/50 grid grid-cols-2 md:grid-cols-3 gap-6 text-[11px] font-mono">
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Heuristic Strategy</span>
                      <div className="flex items-center gap-2 text-blue-300 bg-blue-500/10 px-3 py-1.5 rounded-lg border border-blue-500/20 w-max shadow-inner">
                        <Terminal className="w-3.5 h-3.5" /> {advancedStats.algorithm}
                      </div>
                    </div>
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Data Entropy</span>
                      <div className="text-gray-300 text-sm font-bold">{advancedStats.entropy ? advancedStats.entropy.toFixed(4) : 'N/A'} <span className="text-gray-600 text-[10px]">bits/byte</span></div>
                    </div>
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Security Clearance</span>
                      <div className={clsx("font-black text-sm flex items-center gap-1.5 px-3 py-1.5 rounded-lg border w-max shadow-inner",
                        advancedStats.securityStatus === 'Suspicious' ? "text-red-400 bg-red-400/10 border-red-500/20" : "text-green-400 bg-green-400/10 border-green-500/20")}>
                        {advancedStats.securityStatus === 'Suspicious' ? <ShieldAlert className="w-3.5 h-3.5" /> : <Lock className="w-3.5 h-3.5" />}
                        {advancedStats.securityStatus} ({advancedStats.riskScore}%)
                      </div>
                    </div>
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Compression Percentage</span>
                      <div className="space-y-1.5">
                        <span className="text-gray-600 uppercase tracking-wider block font-bold">Compression Percentage</span>
                        <div className="text-green-400 text-sm font-black italic">{Math.max(0, (1 - advancedStats.compressedSize / advancedStats.originalSize) * 100).toFixed(2)}%</div>
                      </div>
                    </div>
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Transport Payload</span>
                      <div className="text-gray-300 text-sm font-bold">{(advancedStats.compressedSize / 1024).toFixed(2)} <span className="text-gray-600">KB</span></div>
                    </div>
                    <div className="space-y-1.5">
                      <span className="text-gray-600 uppercase tracking-wider block font-bold">Integrity Hash</span>
                      <div className="text-gray-500 text-[9px] truncate w-full">0x{Math.random().toString(16).slice(2, 10)}...[Verified]</div>
                    </div>
                  </div>
                </details>
              </motion.div>
            )}
          </AnimatePresence>

          {/* REAL-TIME PERFORMANCE GRID (Bandwidth Efficiency) */}
          <AnimatePresence>
            {transferStats && (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}
                className="grid grid-cols-2 md:grid-cols-4 gap-5"
              >
                <StatCard label="Input Size" value={`${(transferStats.originalSize / 1024 / 1024).toFixed(2)} MB`} icon={Layers} color="text-gray-400" />
                <StatCard label="Bandwidth Efficiency" value={`${(transferStats.finalSize / 1024).toFixed(1)} KB`} icon={Wifi} color="text-blue-400" />
                <StatCard label="Compression" value={`${transferStats.compressionPercent}%`} icon={Zap} color="text-green-400" />
                <StatCard label="Tunnel Speed" value={`${transferStats.speed || 'N/A'} MB/s`} icon={Activity} color="text-yellow-400" />
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* RIGHT COLUMN: REPOSITORY & LOGS */}
        <div className="lg:col-span-4 space-y-6 flex flex-col h-full">

          {/* DOWNLOADS HUB */}
          {receivedFiles.length > 0 && (
            <motion.div
              initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }}
              className="bg-[#121826] border border-gray-800 rounded-[2.5rem] p-6 shadow-2xl overflow-hidden relative"
            >
              <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-blue-500 to-transparent" />
              <h3 className="text-xs font-black text-gray-500 mb-5 flex items-center gap-3 tracking-[0.2em] uppercase">
                <Download className="w-5 h-5 text-green-500" /> Received Hub
              </h3>
              <div className="space-y-3 max-h-64 overflow-y-auto custom-scrollbar pr-2">
                {receivedFiles.map((f, i) => (
                  <motion.div
                    key={i} layout initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                    className="flex justify-between items-center bg-black/40 p-4 rounded-2xl border border-gray-800/50 hover:border-blue-500/30 transition-all group"
                  >
                    <div className="flex flex-col overflow-hidden">
                      <span className="text-sm text-gray-200 truncate w-40 font-bold tracking-tight">{f.name}</span>
                      <span className="text-[9px] text-gray-600 font-mono italic">{new Date(f.timestamp).toLocaleTimeString()} • Verified</span>
                    </div>
                    <a
                      href={f.url} download={f.name}
                      className="text-blue-500 hover:text-white bg-blue-500/10 hover:bg-blue-600 p-2.5 rounded-xl transition-all shadow-lg active:scale-90"
                    >
                      <Download className="w-5 h-5" />
                    </a>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}

          {/* SYSTEM LOGS TERMINAL */}
          <div className="bg-black border border-gray-800/80 rounded-[2.5rem] p-1 flex-1 flex flex-col min-h-[450px] shadow-[0_30px_60px_-12px_rgba(0,0,0,0.8)] overflow-hidden">
            <div className="px-6 py-4 border-b border-gray-800/50 flex items-center justify-between bg-gradient-to-r from-gray-900 via-gray-900 to-black rounded-t-[2.4rem]">
              <div className="flex items-center gap-3">
                <Terminal className="w-4 h-4 text-blue-500" />
                <span className="text-[10px] font-black text-gray-500 tracking-[0.2em] uppercase">Security Engine Output</span>
              </div>
              <div className="flex gap-2">
                <div className="w-2.5 h-2.5 rounded-full bg-red-500/20" />
                <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/20" />
                <div className="w-2.5 h-2.5 rounded-full bg-green-500/20 animate-pulse" />
              </div>
            </div>
            <div className="flex-1 p-6 font-mono text-[10px] space-y-2 overflow-y-auto custom-scrollbar text-gray-400 bg-[#05070a]">
              {logs.map((l, i) => (
                <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} className="flex gap-3 items-start group">
                  <span className="text-blue-500 font-black opacity-40 group-hover:opacity-100 transition-opacity">»</span>
                  <span className={clsx("leading-relaxed",
                    l.includes('Error') || l.includes('Block') ? "text-red-400 font-bold" :
                      l.includes('Receiving') || l.includes('Mesh') ? "text-blue-400" :
                        l.includes('Ready') || l.includes('Integrated') ? "text-green-400" : "text-gray-500")
                  }>
                    {l}
                  </span>
                </motion.div>
              ))}
              <div className="animate-pulse text-blue-500 font-black pl-1">_</div>
            </div>
          </div>
        </div>
      </div>

      {/* TOAST CONTAINER */}
      <div className="fixed top-24 right-6 z-[100] flex flex-col gap-4 pointer-events-none">
        <AnimatePresence>
          {toasts.map(toast => (
            <motion.div
              key={toast.id}
              initial={{ opacity: 0, x: 50, scale: 0.9 }}
              animate={{ opacity: 1, x: 0, scale: 1 }}
              exit={{ opacity: 0, x: 20, scale: 0.9 }}
              className={clsx(
                "pointer-events-auto flex items-center gap-3 px-5 py-4 rounded-2xl shadow-2xl border backdrop-blur-md min-w-[300px]",
                toast.type === 'success' ? "bg-green-500/10 border-green-500/20 text-green-400" :
                  toast.type === 'error' ? "bg-red-500/10 border-red-500/20 text-red-400" :
                    "bg-blue-500/10 border-blue-500/20 text-blue-400"
              )}
            >
              {toast.type === 'success' ? <CheckCircle className="w-5 h-5 flex-shrink-0" /> :
                toast.type === 'error' ? <XCircle className="w-5 h-5 flex-shrink-0" /> :
                  <Info className="w-5 h-5 flex-shrink-0" />}
              <div>
                <h4 className="font-bold text-sm uppercase tracking-wide">{toast.type}</h4>
                <p className="text-xs font-medium opacity-90">{toast.message}</p>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      {/* MODAL: INCOMING ENCRYPTED REQUEST */}
      <AnimatePresence>
        {incomingRequest && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-md px-6">
            <motion.div
              initial={{ scale: 0.9, opacity: 0, rotateX: 45 }} animate={{ scale: 1, opacity: 1, rotateX: 0 }} exit={{ scale: 0.9, opacity: 0 }}
              className="bg-[#121826] border border-blue-500/30 p-10 rounded-[3rem] shadow-[0_0_100px_rgba(59,130,246,0.2)] max-w-md w-full text-center relative overflow-hidden"
            >
              <div className="absolute -top-24 -left-24 w-48 h-48 bg-blue-500/10 rounded-full blur-3xl" />
              <div className="absolute -bottom-24 -right-24 w-48 h-48 bg-blue-500/10 rounded-full blur-3xl" />

              <div className="w-20 h-20 bg-blue-500/10 rounded-3xl flex items-center justify-center mx-auto mb-6 border border-blue-500/20 shadow-inner">
                <Bell className="w-10 h-10 text-blue-400 animate-bounce" />
              </div>
              <h3 className="text-2xl font-black text-white mb-3 tracking-tighter">Inbound Handshake</h3>
              <p className="text-gray-400 mb-10 leading-relaxed font-medium">
                {/* @ts-ignore */}
                <strong className="text-blue-400">@{incomingRequest.from}</strong> is requesting a secure P2P tunnel initialization.
              </p>
              <div className="flex gap-4">
                <button
                  onClick={() => setIncomingRequest(null)}
                  className="flex-1 py-4 rounded-2xl bg-gray-800 hover:bg-gray-700 text-gray-300 font-black text-xs uppercase tracking-widest transition-all"
                >
                  Reject
                </button>
                <button
                  onClick={acceptRequest}
                  className="flex-1 py-4 rounded-2xl bg-blue-600 hover:bg-blue-500 text-white font-black text-xs uppercase tracking-widest shadow-xl shadow-blue-600/30 transition-all active:scale-95"
                >
                  Authorize
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* PROGRESS TRACKER - Bottom Position */}
      {isTransferring && transferStage !== 'idle' && (
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="fixed bottom-6 left-1/2 -translate-x-1/2 bg-gray-900/90 border border-gray-700/50 p-5 rounded-2xl backdrop-blur z-50 max-w-[85vw]">
          <TransferProgressStages
            currentStage={transferStage}
            isReceiver={receiverPipelineRef.current !== null}
            fileName={currentFileName}
          />
        </motion.div>
      )}

    </div>
  );
};

// --- SUBSIDIARY COMPONENT: PERFORMANCE CARD (3D STYLE) ---
const StatCard = ({ label, value, icon: Icon, color }: any) => (
  <div className="bg-gradient-to-b from-[#1a1f2e] to-[#121826] border border-black/60 p-6 rounded-[1.5rem] flex flex-col justify-between h-32 shadow-[0_15px_30px_-5px_rgba(0,0,0,0.6)] hover:border-gray-700 transition-all group overflow-hidden relative active:scale-95">
    {/* Inner highlight for convexity */}
    <div className="absolute inset-x-0 top-0 h-px bg-white/10" />

    <div className="absolute top-0 right-0 p-2 opacity-5 group-hover:opacity-10 transition-opacity"><Icon className="w-16 h-16" /></div>
    <div className="flex items-center justify-between mb-3 relative z-10">
      <span className="text-[9px] font-black text-gray-500 uppercase tracking-widest leading-none">{label}</span>
      <div className={clsx("p-2 rounded-lg bg-black/40 shadow-inner border border-white/5", color)}><Icon className="w-4 h-4" /></div>
    </div>
    <span className="text-xl font-black text-gray-100 tracking-tighter tabular-nums relative z-10">{value}</span>
  </div>
);